<!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_launcher (#PCDATA)>		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>			<emu_name>Sega 32X</emu_name>			<emu_parser>NoIntro_parser.xml</emu_parser>			<emu_description>No-Intro_32X</emu_description>			<emu_category>Sega</emu_category>			<emu_version>08102015</emu_version>			<emu_date>03/03/2015</emu_date>			<emu_author>no-intro</emu_author>			<emu_homepage>http://www.no-intro.org</emu_homepage>			<emu_baseurl>http://archive.org/download/No-Intro-Collection_2015-03-03/Sega%20-%2032X.zip/Sega%20-%2032X%2F</emu_baseurl>			<emu_launcher>retroplayer</emu_launcher>			<emu_ext_launch_cmd>none</emu_ext_launch_cmd>			<emu_downloadpath>default</emu_downloadpath>			<emu_postdlaction>unzip_rom</emu_postdlaction>			<emu_comment>No Intro Sega 32X List by Zach Morris, removed all beta, and Non-USA games.The Sega 32X, codenamed Project Mars, is an add-on for the Mega Drive/Genesis video game console by Sega. Its aim was to increase the lifespan of the aging Mega Drive/Genesis system, which was facing stiff competition from the SNES. While connecting it to Mega Drive did increase its capabilities, reluctance to adapt due to the previous failure of the Mega-CD and the upcoming Sega Saturn system led to low sales and a short lifespan. It was distributed under the name Sega Super 32X in Japan, Sega Genesis 32X in North America, Sega Mega Drive 32X in the PAL region, and Sega Mega 32X in Brazil.Developer:  SegaManufacturer:  SegaCPU:  2 × SH-2 32-bit RISCMemory:  256 kB program RAMGraphics:  N/ASound:  Stereo 10-bit PWM (Pulse Width Modulation)Display:  320 × 240Media:  CartridgeMax. Controllers:  2			</emu_comment>			<emu_thumb>http://thegamesdb.net/banners/platform/boxart/33-1.jpg</emu_thumb>			<emu_banner>http://thegamesdb.net/banners/platform/banners/33-1.jpg</emu_banner>			<emu_fanart>http://upload.wikimedia.org/wikipedia/commons/a/a0/Sega-Genesis-Model2-32X.jpg</emu_fanart>			<emu_logo>http://upload.wikimedia.org/wikipedia/en/6/6c/Sega_32X_logo.png</emu_logo>			<emu_trailer>kxVOpWNlbDE</emu_trailer>		</header>			<game name="32X Sample Program - PWM Sound Demo (USA) (SDK Build)">					<description>32X Sample Program - PWM Sound Demo (USA) (SDK Build)</description>					<rom crc="542ad12e" name="32X Sample Program - PWM Sound Demo (USA) (SDK Build).zip" size="524288"/>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4752-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4752-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4752.png</clearlogo1>			</game>			<game name="After Burner Complete ~ After Burner (Japan, USA)">					<description>After Burner Complete ~ After Burner (Japan, USA)</description>					<rom crc="204044c4" name="After Burner Complete ~ After Burner (Japan, USA).zip" size="2097152"/>					<plot>Strap into your lethal F14 Tomcat, kick-in the afterburner and set the skies alight!  You fly through multiple day and night missions over land and sea, picking off enemy targets as you lock and launch your deadly Sidewinder missiles.</plot>					<genre>Flight SimulatorShooter</genre>					<nplayers>1</nplayers>					<studio>Sega</studio>					<releasedate>01/13/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/4912-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4912-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4912-1.jpg</boxart1>			</game>			<game name="Amazing Spider-Man, The - Web of Fire (USA)">					<description>Amazing Spider-Man, The - Web of Fire (USA)</description>					<rom crc="29dce257" name="Amazing Spider-Man, The - Web of Fire (USA).zip" size="3145728"/>					<plot>The game features side-scrolling action in which Spider-Man has to take on various enemy types which want to kill him. Besides the usual range of melee kicks and punches, he also sticks to walls and uses special attacks based on his web fluid. Creating spider web &quot;vines&quot; are used to swing from building to building; either required to cross gaps or simply to progress faster in the levels. Every use of his fluid decreases a web bar which, just like health, is refilled by picking up items floating in the game world. The first goal of the game is to rescue the superhero Daredevil, who then continues to help Spider-Man out: after activating the associated special attack, Daredevil covers the screen with his attacks.</plot>					<studio>Sega</studio>					<releasedate>01/01/1996</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/4925-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4925-2.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4925-2.jpg</boxart1>			</game>			<game name="BC Racers (USA)">					<description>BC Racers (USA)</description>					<rom crc="936c3d27" name="BC Racers (USA).zip" size="3145728"/>					<plot>Its pre-hysterical!  Millionaire playboy caveman Millstone Rockafella arranges a wild n wacky BC bike race, the winner of which receives the ultimate boulderdash bike.  Cool n crazy Cliff Ace has had his sunglasses set on a boulderdash bike since he was knee-high, so he signs up for the race - taking his cave-babe Roxy along for the ride!  The 32X pushes graphics to the limit with 256 colors for in-game graphics and full 24-bit for static display.  The stone-age never looked better!</plot>					<genre>Racing</genre>					<nplayers>2</nplayers>					<studio>Front Street</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4913-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4913-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4913.png</clearlogo1>			</game>			<game name="Blackthorne (USA)">					<description>Blackthorne (USA)</description>					<rom crc="d1a60a47" name="Blackthorne (USA).zip" size="3145728"/>					<videoid>YW-HYI-wqts</videoid>					<plot>Through the dark vastness of space, exiled prince Kyle Blackthorne returns to Tuul to avenge his murdered father and restore the shattered Lightstone.  The conqueror Sarlac opposes his vicious troops against the enraged prince.  But the evil lord will soon find out an army is not enough against a single fierce fighter with a vengeance!</plot>					<genre>ActionPlatform</genre>					<nplayers>1</nplayers>					<studio>Interplay</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9074-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9074-1.jpg</boxart1>			</game>			<game name="Brutal Unleashed - Above the Claw (USA)">					<description>Brutal Unleashed - Above the Claw (USA)</description>					<rom crc="7a72c939" name="Brutal Unleashed - Above the Claw (USA).zip" size="3145728"/>					<plot>Under the watchful eye of the great master Dali Llama, the worlds greatest martial artists would return to a place they knew well Brutal Island.  Each will use their own unique mental and physical martial arts style and training, in a tournament to prove the worlds one true champion.Brutal, Above the Claw, is a brilliantly rendered game of humorous cartoon style combat, combined with depth, philosophy, and an attention to detail not found in any other fighting game.Go ahead and Unleash the Animal, its time to get Brutal.</plot>					<genre>Fighting</genre>					<nplayers>2</nplayers>					<studio>GameTek</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/5295-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/5295-1.jpg</boxart1>			</game>			<game name="Chaotix ~ Knuckles' Chaotix (Japan, USA)">					<description>Chaotix ~ Knuckles' Chaotix (Japan, USA)</description>					<rom crc="d0b0b842" name="Chaotix ~ Knuckles' Chaotix (Japan, USA).zip" size="3145728"/>					<plot>A mysterious island rose from the sea shortly after the events of Sonic &amp; Knuckles. Dr. Robotnik discovered the island, and found a mysterious ring inscribed with descriptions of the Chaos Rings, ancient Rings infused with Chaos Emerald energy. In order to find these Rings, Robotnik built his base, the Newtrogic High Zone, on the island. Mighty the Armadillo, Espio the Chameleon, Vector the Crocodile, and Charmy Bee also arrived at the island, and ended up being captured by Robotnik and Metal Sonic, and placed in Robotnik's Combi Catcher machine. Knuckles, curious about the strange island, goes there as well, and manages to rescue Espio. The two then go on to stop Robotnik from getting the Chaos Rings.</plot>					<genre>Platform</genre>					<nplayers>1</nplayers>					<studio>Sega</studio>					<releasedate>04/21/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/2290-1.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/2290-1.jpg</snapshot1>			</game>			<game name="Cyber Brawl ~ Cosmic Carnage (Japan, USA)">					<description>Cyber Brawl ~ Cosmic Carnage (Japan, USA)</description>					<rom crc="7c7be6a2" name="Cyber Brawl ~ Cosmic Carnage (Japan, USA).zip" size="3145728"/>					<plot>Cosmic Carnage is a one-on-one fighting game set in outer space. The story begins as a prison barge is hijacked by it's cargo in an escape attempt. The resulting chaos caused the barge to crash into a military cruiser. The impact caused extensive damage to both ships. There were only 8 survivors, 4 from each ship. What's worse, there's only one escape pod. You control one of the 8 survivors, and have to finish off all the others to escape with your life.</plot>					<genre>Fighting</genre>					<nplayers>2</nplayers>					<studio>Sega</studio>					<releasedate>03/02/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4914-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4914-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/4914-1.jpg</snapshot1>			</game>			<game name="Doom (Japan, USA)">					<description>Doom (Japan, USA)</description>					<rom crc="208332fd" name="Doom (Japan, USA).zip" size="3145728"/>					<plot>All Hell has run amok!  Monstrous demons from another dimension use their gruesome talents to turn your space station into a blood-splattered slaughterhouse.They got black magic.  You got firepower.  Fireballs and lost souls face shotguns, chainsaws, and rocket launchers!Butcher the hordes of Hell.  Or get butchered, if you dont have the skill and pure guts to save your skin!</plot>					<genre>Shooter</genre>					<studio>Sega</studio>					<releasedate>01/01/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/4917-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/4917-2.jpg</fanart2>					<fanart3>http://thegamesdb.net/banners/fanart/original/4917-3.jpg</fanart3>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4917-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4917-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/4917-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/4917-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4917.png</clearlogo1>			</game>			<game name="ECCO the Dolphin CinePak Demo (Japan, USA) (Developer Cart)">					<description>ECCO the Dolphin CinePak Demo (Japan, USA) (Developer Cart)</description>					<rom crc="b06178df" name="ECCO the Dolphin CinePak Demo (Japan, USA) (Developer Cart).zip" size="3145728"/>					<fanart1>http://thegamesdb.net/banners/fanart/original/4917-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/4917-2.jpg</fanart2>					<fanart3>http://thegamesdb.net/banners/fanart/original/4917-3.jpg</fanart3>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4917-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4917-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/4917-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/4917-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4917.png</clearlogo1>			</game>			<game name="Golf Magazine 36 Great Holes Starring Fred Couples (Japan, USA)">					<description>Golf Magazine 36 Great Holes Starring Fred Couples (Japan, USA)</description>					<rom crc="d3d0a2fe" name="Golf Magazine 36 Great Holes Starring Fred Couples (Japan, USA).zip" size="3145728"/>					<plot>There are seven different modes (Stroke Play, Tournament, Skins, Shoot-out, Scramble, Practice and Match Play) and three different types of golf club heads including wood, metal and graphite. There is a battery back-up to keep track of 16 different categories of stats and does feature the voice of Fred Couples, even though he is not a playable character.</plot>					<genre>Sports</genre>					<studio>SEGA</studio>					<releasedate>01/01/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4911-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4911-1.jpg</boxart1>			</game>			<game name="Kolibri (USA, Europe)">					<description>Kolibri (USA, Europe)</description>					<rom crc="20ca53ef" name="Kolibri (USA, Europe).zip" size="3145728"/>					<plot>Kolibri is a hummingbird hero in this unusual side scrolling shooter for the 32X. Deep inside the earth's core, there is a crystal from another world. This crystal is the earth's life force, and essential to it's survival. One day, a dark crystal falls from the sky and damages the earth's crystal. Desperate, the earth's crystal rockets to the surface and empowers Kolibri with the abilities he needs to defeat the dark crystal.</plot>					<genre>Shooter</genre>					<nplayers>1</nplayers>					<studio>Sega</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Mars Check Program Version 1.0 (Japan, USA) (SDK Build) (Set 2)">					<description>Mars Check Program Version 1.0 (Japan, USA) (SDK Build) (Set 2)</description>					<rom crc="a2da35fd" name="Mars Check Program Version 1.0 (Japan, USA) (SDK Build) (Set 2).zip" size="65536"/>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Mars Check Program Version 1.0 (Japan, USA) (SDK Build) (Set 1)">					<description>Mars Check Program Version 1.0 (Japan, USA) (SDK Build) (Set 1)</description>					<rom crc="8f7260fb" name="Mars Check Program Version 1.0 (Japan, USA) (SDK Build) (Set 1).zip" size="4194304"/>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Mars Sample Program - Gnu Sierra (Japan, USA) (SDK Build)">					<description>Mars Sample Program - Gnu Sierra (Japan, USA) (SDK Build)</description>					<rom crc="5f0df42c" name="Mars Sample Program - Gnu Sierra (Japan, USA) (SDK Build).zip" size="655360"/>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Mars Sample Program - Pharaoh (Japan, USA) (SDK Build)">					<description>Mars Sample Program - Pharaoh (Japan, USA) (SDK Build)</description>					<rom crc="969c80d4" name="Mars Sample Program - Pharaoh (Japan, USA) (SDK Build).zip" size="262144"/>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Mars Sample Program - Runlength Mode Test (Japan, USA) (SDK Build)">					<description>Mars Sample Program - Runlength Mode Test (Japan, USA) (SDK Build)</description>					<rom crc="d630e343" name="Mars Sample Program - Runlength Mode Test (Japan, USA) (SDK Build).zip" size="262144"/>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Mars Sample Program - Texture Test (Japan, USA) (SDK Build)">					<description>Mars Sample Program - Texture Test (Japan, USA) (SDK Build)</description>					<rom crc="9b2ad63f" name="Mars Sample Program - Texture Test (Japan, USA) (SDK Build).zip" size="24576"/>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2609-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2609-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2609-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/2609-2.jpg</snapshot2>			</game>			<game name="Metal Head (Japan, USA) (En,Ja)">					<description>Metal Head (Japan, USA) (En,Ja)</description>					<rom crc="ef5553ff" name="Metal Head (Japan, USA) (En,Ja).zip" size="3145728"/>					<plot>Metal Head is a bit of a variation on the usual giant robot combat game. The game's mission areas bear more resemblance to a first-person shooter than a simulation. The graphics are all rendered in texture mapped polygons, which is unusual for a 32X game.</plot>					<genre>Action</genre>					<studio>Sega</studio>					<releasedate>02/24/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4918-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4918-1.jpg</boxart1>			</game>			<game name="Mortal Kombat II (Japan, USA)">					<description>Mortal Kombat II (Japan, USA)</description>					<rom crc="773c0a85" name="Mortal Kombat II (Japan, USA).zip" size="4194304"/>					<plot>Following his failure to defeat Liu Kang in the first Mortal Kombat game, the evil sorcerer Shang Tsung begs his master, Shao Kahn, to spare his life. He tells Shao Kahn that the invitation for Mortal Kombat cannot be turned down, and if they hold it in Outworld, the Earthrealm warriors must attend. Kahn agrees to this plan, and even restores Tsung's youth. He then extends the invitation to Raiden, who gathers his warriors and takes them into Outworld. The new tournament is much more dangerous, as Shao Kahn has the home field advantage, and an Outworld victory will allow him to subdue Earthrealm.</plot>					<genre>Fighting</genre>					<studio>Midway</studio>					<releasedate>12/04/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/4919-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/4919-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4919-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4919-1.jpg</boxart1>					<banner1>http://thegamesdb.net/banners/graphical/4919-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4919.png</clearlogo1>			</game>			<game name="Motocross Championship (USA)">					<description>Motocross Championship (USA)</description>					<rom crc="a21c5761" name="Motocross Championship (USA).zip" size="2097152"/>					<plot>Motocross Championship is the only dirtbike racing game for the 32X. The action takes place from a behind-the-bike perspective, and makes use of the 32X's hardware bitmap scaling to present a 3D graphical effect.</plot>					<genre>Racing</genre>					<nplayers>2</nplayers>					<studio>Sega</studio>					<releasedate>01/01/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9076-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9076-1.jpg</boxart1>			</game>			<game name="NBA Jam - Tournament Edition (World)">					<description>NBA Jam - Tournament Edition (World)</description>					<rom crc="6b7994aa" name="NBA Jam - Tournament Edition (World).zip" size="4194304"/>					<plot>Up to four human players can take part, each always controlling a single player for their team, and AI for missing players. This allows for four players to face each other in teams of two, or for two players to team up against a third player with a CPU team-mate.The Tournament Edition ups each team's roster to three players, and allows for substitutions between quarters. Shoving players now results in injuries, which lower a player's stats; encouraging you to sub them out and let them recover. Aside from the usual secret characters and cheat modes, the T.E. also includes four new additions you can individually enable from the special options menu.</plot>					<genre>Sports</genre>					<nplayers>4+</nplayers>					<studio>Acclaim</studio>					<releasedate>05/01/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/9077-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9077-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9077-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/9077.png</clearlogo1>			</game>			<game name="NFL Quarterback Club (World)">					<description>NFL Quarterback Club (World)</description>					<rom crc="0bc7018d" name="NFL Quarterback Club (World).zip" size="3145728"/>					<plot>NFL Quarterback Club, called NFL Quarterback Club '95 in Japan, is an American football game released for the Sega Mega Drive, Sega 32X and Sega Game Gear. It was the first in the NFL Quarterback Club series and was followed by NFL Quarterback Club 96.</plot>					<genre>Sports</genre>					<nplayers>4+</nplayers>					<studio>Acclaim</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/14262-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/14262-1.jpg</boxart1>			</game>			<game name="Parasquad ~ Zaxxon's Motherbase 2000 (Japan, USA)">					<description>Parasquad ~ Zaxxon's Motherbase 2000 (Japan, USA)</description>					<rom crc="447d44be" name="Parasquad ~ Zaxxon's Motherbase 2000 (Japan, USA).zip" size="2097152"/>					<plot>This 32X-exclusive sci-fi shooter is similar gameplay-wise to Sega's arcade game Zaxxon. The graphics consist of a diagonally scrolling playfield which creates a pseudo 3D environment. The backgrounds are drawn using 2D scrolling planes, but the enemy and ship objects are drawn using 3D flat-shaded polygons.Although the basic goal of each of the 9 levels is to shoot everything without getting shot, the game has a strategic element. Your basic spacecraft has very little firepower, and can only sustain one hit. To make matters worse, there are very few power-ups. In order to survive, you have to jump on top of enemies and take control of their weapons systems. This system allows for a large variety of player-controllable ships.</plot>					<genre>Shooter</genre>					<nplayers>2</nplayers>					<studio>Sega</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9083-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9083-1.jpg</boxart1>			</game>			<game name="Pitfall - The Mayan Adventure (USA)">					<description>Pitfall - The Mayan Adventure (USA)</description>					<rom crc="f9126f15" name="Pitfall - The Mayan Adventure (USA).zip" size="3145728"/>					<plot>Pitfall: The Mayan Adventure is a side-scrolling action game in which you play adventurer Pitfall Harry Jr in search of his father Pitfall Harry. You battle your way through the Mayan jungles, waterfalls, deserted mines and can bungee jump and boomerang your way to safety. There are 13 levels and the action is fast and gripping. You will need to be attentiveand quick. Or prepare to die.</plot>					<studio>Activision</studio>					<releasedate>10/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/9079-1.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/9079-1.jpg</snapshot1>			</game>			<game name="Primal Rage (USA, Europe)">					<description>Primal Rage (USA, Europe)</description>					<rom crc="e78a4d28" name="Primal Rage (USA, Europe).zip" size="4194304"/>					<plot>Primal Rage is a one-on-one fighting game featuring dinosaurs and giant apes as the fighters. The graphics are done with digitized stop-motion animation. Gameplay is similar to Mortal Kombat in that it is viewed from a side perspective, and features deadly finishing moves at the end of the match.</plot>					<genre>Fighting</genre>					<nplayers>2</nplayers>					<studio>Time Warner</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4922-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4922-1.jpg</boxart1>					<banner1>http://thegamesdb.net/banners/graphical/4922-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4922.png</clearlogo1>			</game>			<game name="RBI Baseball '95 (USA)">					<description>RBI Baseball '95 (USA)</description>					<rom crc="ff795fdc" name="RBI Baseball '95 (USA).zip" size="2097152"/>					<plot>This version is an updated follow-up to the R.B.I. serie