<?xml version="1.0" ?><!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart20 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>					<emu_name>eXoDOS - Adventure Games</emu_name>					<emu_parser>NoIntro_parser.xml</emu_parser>					<emu_description>eXoDOS_Adventure</emu_description>					<emu_category>PC</emu_category>					<emu_version>1.6</emu_version>					<emu_date>06/01/2013</emu_date>					<emu_author>eXoDOS</emu_author>					<emu_homepage>https://archive.org/details/eXoDOSAdv.v1.6</emu_homepage>					<emu_baseurl>http://archive.org/download/eXoDOSAdv.v1.6/eXoDOSAdv.v1.6.zip/eXoDOSAdv%2FGames%2F</emu_baseurl>					<emu_downloadpath>default</emu_downloadpath>					<emu_postdlaction>None</emu_postdlaction>					<emu_comment>eXoDOS is an attempt to catalog, obtain, and make playable every game developed for the DOS and PC Booter platform. They strive to find original media rather than using scene rips. This collection uses a combination of Dosbox and ScummVM to play these older titles on modern systems.</emu_comment>					<emu_thumb>https://lh5.ggpht.com/l77JyXEQYPZDepw_8xiFN_c4H4-5siFlDjgaxsaUoJlLZ_AED7OUGBqW7AHGYm99QK0=w600</emu_thumb>					<emu_banner>http://www.dosbox.com/site_images/upper_logo.png</emu_banner>					<emu_fanart>https://upload.wikimedia.org/wikipedia/commons/6/69/IBM_PC_5150.jpg</emu_fanart>					<emu_logo>https://upload.wikimedia.org/wikipedia/commons/d/dd/DOSBox_icon.png</emu_logo>					<emu_trailer>wg6htyoZ-Qg</emu_trailer>					</header>			<game name="11th Hour, The (1995)">					<description>11th Hour, The (1995)</description>					<rom name="11th Hour, The (1995).zip" size="2420791239"/>							<plot>The 11th Hour is a 1995 interactive movie puzzle adventure game with a horror setting. It is the sequel to the 1993 game The 7th Guest. It was developed by Trilobyte and used a later version of the &quot;Groovie&quot; graphic engine than that used by The 7th Guest. The 11th Hour also features the music of George &quot;The Fat Man&quot; Sanger and Team Fat.[CR] - CHEATS - [CR]Warp to locations in the game[CR]On the skull screen when starting the game, type one of the following codes to warp to various locations in the game.   Be sure to include the capital letters, and the space bar after each word:[CR]Hidden video[CR]Go to the television In Dutton's room at a point where you can see the close-up view.  Type Kellyn to see a hidden video.  [CR]</plot>					<genre>AdventureHorrorPuzzle</genre>					<releasedate>11/30/1995</releasedate>					<nplayers>1</nplayers>					<videoid>gq0huYRL_hg</videoid>					<fanart1>http://thegamesdb.net/banners/fanart/original/13081-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/13081-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/0/8/3/8083_front.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/13081-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/13081-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/13081-3.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/9/6/a/gfs_50520_1_1_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/5/a/f/gfs_50520_1_2_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/f/6/b/gfs_50520_2_1_mid.jpg</snapshot6>			</game>			<game name="20,000 Leagues Under the Sea (1988)">					<description>20,000 Leagues Under the Sea (1988)</description>					<rom name="20,000 Leagues Under the Sea (1988).zip" size="290597"/>							<plot>The game is based on an 1870 novel by Jules Verne.On July 5th, 1867 the government decided to launch the famous ship the &quot;Abraham Lincoln&quot;, which will leave on the trail of a sea monster. The great French professor Mr. Arronax will also take part in the expedition. The weeks passed without any sign of the monster's presence in the area, when, one day, 300 miles from the shores of Queen Charlotte's Island... three members of the expedition set out on board the Nautilus, a submarine navigated by Captain Nemo. The player takes Anorax's role to find out more.Most of the game is spent on the Nautilus, which consists of three rooms: the living room, the control room and the library. There the player can manipulate objects and talk to people to receive hints what to do next and the state of the Nautilus. With the map, he influences the route. Sometimes the player leaves the submarine to explore other locations, and respectively solves puzzles to receive more hints or to solve action sequences, e.g., fighting against a shark.The game is played in real-time, which means the key to success is being in the right location at the right time. This also results in various possibilities to render the game unwinnable, and causes waiting times. For the same reason, the player also needs to watch Nemo's mood. If he angers Nemo, e.g., by manipulating the ship instruments, he locks the player into his room and valuable time passes. The game is played completely in point &amp; click and has no function to save progress.</plot>					<genre>Adventure</genre>					<releasedate>01/01/1988</releasedate>					<nplayers>1</nplayers>					<videoid>xjgQmaZmGl0</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/21373-1.jpg</boxart1>			</game>			<game name="221B Baker Street (1987)">					<description>221B Baker Street (1987)</description>					<rom name="221B Baker Street (1987).zip" size="264457"/>							<plot>Sherlock Holmes, Dr. Watson, Irene Adler, and Inspector Lestrade must solve thirty of the most difficult and intriguing cases to ever test their abilities. Each sleuth thinks he or she is the most capable of finding the solutions, so they've decided to turn each mystery into a friendly competition of their skills.</plot>					<genre>Miscellaneous</genre>					<releasedate>1987</releasedate>					<videoid>6sLEVR_GmPA</videoid>					<boxart1>http://img.gamefaqs.net/box/8/5/5/303855_front.jpg</boxart1>			</game>			<game name="3 Skulls of the Toltecs (1996)">					<description>3 Skulls of the Toltecs (1996)</description>					<rom name="3 Skulls of the Toltecs (1996).zip" size="217656892"/>							<plot>3 Skulls of the Toltecs is an Adventure game, developed by Revistronic and published by Time Warner Interactive,  which was released in Europe in 1996.</plot>					<genre>Adventure</genre>					<releasedate>1996</releasedate>					<videoid>BmZTiLWzNwk</videoid>					<snapshot1>http://img.gamefaqs.net/screens/f/f/b/gfs_109198_2_1_mid.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/3/3/e/gfs_109198_2_2_mid.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/7/7/d/gfs_109198_2_3_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/a/b/4/gfs_109198_2_4_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/e/f/7/gfs_109198_2_5_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/2/3/2/gfs_109198_2_6_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/6/f/4/gfs_109198_2_7.jpg</snapshot7>			</game>			<game name="3D Dinosaur Adventure (1988)">					<description>3D Dinosaur Adventure (1988)</description>					<rom name="3D Dinosaur Adventure (1988).zip" size="4546003"/>							<plot>4x4 Cabela Off-Road Adventure 3 oferece 18 veculos off-road equipadas para lidar com as condies de risco encontrados durante o mundo spero e pronto de conduo fora de estrada.  Ambientes incluem Baja, albufeira, mata norte, crculo rtico, montanha, rio seco e um nvel secreto.  Os jogadores iro escolher entre mais de 12 peas intercambiveis, incluindo pratos de derrapagem, guardas de pra-choques, faris e pneus para encontrar uma combinao de trabalho para cada curso.  Avarias mecnicas - eixos quebrados, peas de motor rachadas, e problemas eltricos - vai afligir motoristas e deve ser corrigido.</plot>					<genre>Racing</genre>					<releasedate>06/18/2003</releasedate>					<nplayers>1</nplayers>					<videoid>gnSUk6wrrd8</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/19137-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/9/7/5/60975_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/19137-1.jpg</boxart3>					<snapshot1>http://thegamesdb.net/banners/screenshots/19137-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/19137-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/19137-3.jpg</snapshot3>			</game>			<game name="7th Guest, The (1993)">					<description>7th Guest, The (1993)</description>					<rom name="7th Guest, The (1993).zip" size="744978086"/>							<plot>Henry Stauf's mansion had been abandoned for as long as anyone dare remember. Stauf was a master toy maker, a maker of amazing puzzles and this strange house was his greatest creation. Now, the mansion stands empty, rotting ever since the children started dying, ever since the six guests came. Now there are only the eerie lights and the terrible sing-song rhymes of the children... And suddenly, you are in the house. You move from room to haunted room, step by terrifying step, as scenes from that night of horror come to life. Because Stauf's game isn't over. There were six guests the world knew about - and there was one other. Stauf's mad mansion lives again. And only you can end the nightmare and learn the secret of The 7th Guest.[CR] - CHEATS - [CR]Unlock all rooms[CR]When you first start the game, type on your keyboard on the menu screen ''Zaphod Beeblebrox'' including the casing and space and if done correctly you hear the words ''groovy''. Now you click on one of the 4 corners of the ouija board and it opens up a picture list of all the rooms.[CR]</plot>					<genre>AdventurePuzzle</genre>					<releasedate>01/01/1993</releasedate>					<nplayers>1</nplayers>					<videoid>P5-QKu87MIA</videoid>					<fanart1>http://thegamesdb.net/banners/fanart/original/13080-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/13080-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/7/6/2/14762_front.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/13080-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/13080-2.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/2/d/0/gfs_28415_1_1.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/8/4/d/gfs_28415_2_1.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/d/8/a/gfs_28415_2_2_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/b/2/d/gfs_28415_2_3.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/7/3/d/gfs_28415_2_4.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/0/4/3/gfs_28415_2_5_mid.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/4/5/d/gfs_28415_2_6.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/d/e/d/gfs_28415_2_7.jpg</snapshot10>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/13080.png</clearlogo1>			</game>			<game name="905 (2000)">					<description>905 (2000)</description>					<rom name="905 (2000).zip" size="67870"/>					</game>			<game name="A Day for Soft Food (1999)">					<description>A Day for Soft Food (1999)</description>					<rom name="A Day for Soft Food (1999).zip" size="157508"/>							<plot>Fast Food Tycoon tests the player's culinary expertise and management skills. One creates his/her own character through balancing personal traits and experience, at the expense of age and starting money. The game provides more than 800,000 different character possibilities. The gameplay can be both open-ended or object-oriented. The player determines the conditions and objectives of the game during player configuration.The player must manage and decide branch-location, pizza recipes, interior design, global marketing and fast food advertising strategies, employees, and out-competing rivals. The player has control of every aspect of the game, from the type of seating used in the branches to the medium of advertisement. The player can even choose what bank to invest/borrow from.</plot>					<genre>Construction and Management SimulationStrategy</genre>					<releasedate>11/30/2000</releasedate>					<videoid>AzBnu-BKalY</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/25498-1.jpg</boxart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/25498-1.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/25498-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/25498-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/25498-3.jpg</snapshot3>			</game>			<game name="A Dudley Dilemma (1988)">					<description>A Dudley Dilemma (1988)</description>					<rom name="A Dudley Dilemma (1988).zip" size="785878"/>							<plot>The Global Dilemma: Guns or Butter is a Strategy game, developed by Mindscape Inc. and published by IBM,  which was released in 1990.</plot>					<genre>Strategy</genre>					<releasedate>1990</releasedate>					<videoid>nJwRKaNWjH4</videoid>			</game>			<game name="A Mind Forever Voyaging (1985)">					<description>A Mind Forever Voyaging (1985)</description>					<rom name="A Mind Forever Voyaging (1985).zip" size="264848"/>							<plot>It's 1031. The world is on the brink of chaos. In the United States of North America, spiraling crime and unemployment rates, decayed school systems and massive government regulations have led to a lazy, contentious society. To reverse this critical situation, government and industry leaders have developed a Plan combining the economic freedom and strong moral values of the 1950's with the technological advancements of the 21st century. Will the Plan ensure peace and prosperity? Or will it set the earth on a suicide course to destruction? As the world's first conscious, intelligent computer, only you can visit places that have never been seen before. Only you can view the future. And only you know what must be done to save humanity. A major departure for Infocom, A Mind Forever Voyaging is reminiscent of such classic works of science fiction as Brave New World and 1984. You'll spend less time solving puzzles, as you explore realistic worlds of the future.</plot>					<genre>Adventure</genre>					<releasedate>1985</releasedate>					<nplayers>1</nplayers>					<videoid>99M3IdfOgB8</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/19948-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/6/3/4/23634_front.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/19948-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/19948-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/19948-3.jpg</snapshot3>			</game>			<game name="Abbey, The (1993)">					<description>Abbey, The (1993)</description>					<rom name="Abbey, The (1993).zip" size="50996"/>							<plot>Thou Shalt Not Kill. Monks, murder, and above all, suspense. An old abbey is the scene of a series of mysterious murders, and only one man can put a stop to the slaughter. Former Grand Inquisitor Leonardo and his assistant Bruno are sent by the Vatican to the isolated abbey to investigate the strange goings-on surrounding a carefully guarded secret. Yet hardly have they arrived when their quest is overshadowed by an attempt on their lives&amp;hellip; Murder in the Abbey is a mystery of cinematic proportions whose suspense goes far beyond that of a conventional adventure game!</plot>					<genre>AdventurePuzzle</genre>					<releasedate>01/01/1993</releasedate>					<nplayers>1</nplayers>					<videoid>wDTNw-Ajp9c</videoid>					<boxart1>http://img.gamefaqs.net/box/4/9/3/103493_front.jpg</boxart1>			</game>			<game name="Acheton (1978)">					<description>Acheton (1978)</description>					<rom name="Acheton (1978).zip" size="128218"/>							<plot>Acheton is an Adventure game, developed and published by Topologika,  which was released in 1987.</plot>					<genre>Adventure</genre>					<releasedate>1987</releasedate>					<boxart1>http://img.gamefaqs.net/box/4/4/0/96440_front.jpg</boxart1>			</game>			<game name="Ad Verbum (2000)">					<description>Ad Verbum (2000)</description>					<rom name="Ad Verbum (2000).zip" size="162003"/>							<plot>Return to the dawn of a New World in an intense saga of adventure and discovery. You'll begin your journey by setting sail for a New World in anticipation of seeking out wealth and power and settling a new nation and empire. Along the way, you'll interact with nine different cultures, including Africans, Aztecs, and Native Americans, and trade goods and services with them to meet the needs of your people. Combat takes place on dry land as well as at sea, where your fleet of merchant ships must defend against pirates determined to take over your goods.[CR] - CHEATS - [CR]Get more money[CR]WARNING: Create Backup file before doing. [CR]</plot>					<genre>Strategy</genre>					<releasedate>2003</releasedate>					<boxart1>http://img.gamefaqs.net/box/3/7/2/11372_front.jpg</boxart1>			</game>			<game name="Advanced Xoru (1989)">					<description>Advanced Xoru (1989)</description>					<rom name="Advanced Xoru (1989).zip" size="138513"/>							<plot>NetWars was an IPX-based 3D vector-graphics computer game released by Novell in 1993 for DOS to demonstrate NetWare capabilities. It was written by Edward Hill, one of Novell's engineers in its European Development Centre (EDC) in Hungerford, UK. Development had started in 1989.Since 1997, a much improved version  named Advanced NetWars shipped with Caldera OpenDOS 7.01, DR-DOS 7.02 and DR-DOS 7.03.[2] It added support for SoundBlaster sound, Joystick control, up to six players in multi-player mode, missiles and computer-controlled ships in multi-player mode, and it featured a new multi-player shoot-out mode, an improved single-player mode, an external view mode, as well as a shape editor to design own space-ships.[2] Despite all these additions, the executable maintained a file size of less than 77 KB.</plot>					<genre>Shooter</genre>					<releasedate>01/16/2014</releasedate>					<nplayers>4+</nplayers>			</game>			<game name="Adventure XT (2007)">					<description>Adventure XT (2007)</description>					<rom name="Adventure XT (2007).zip" size="46192"/>							<plot>Create your own theme park just the way you want it. Let your imagination run wild! Attract visitors to your park with all kinds of different and unusual attractions. Your revenue and the reactions of your visitors help you to expand your park and make it even more attractive. Turn your park into the best and most exciting theme park of all time!</plot>					<genre>Construction and Management SimulationSandboxStrategy</genre>					<releasedate>11/08/2013</releasedate>					<nplayers>1</nplayers>					<videoid>ZqTr090xsWw</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/28866-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/4/7/6/23476_front.jpg</boxart2>			</game>			<game name="Adventure in Humongous Cave (1993)">					<description>Adventure in Humongous Cave (1993)</description>					<rom name="Adventure in Humongous Cave (1993).zip" size="437165"/>							<plot>CAVE! CAVE! DEUS VIDET. is an art-fi episodic visual novel inspired by the works of Jheronimus Bosch. The game features musings about Bosch's own work compounded with stark modern visuals.From the official website:Strange things happen in Episode 0 when 17-year-old punk rocker Hoodie meets a weird man who seems to know too much about the world(s) of 16th century Dutch painter Jheronimus Bosch.</plot>					<genre>Puzzle</genre>					<releasedate>07/15/2013</releasedate>					<nplayers>1</nplayers>					<videoid>Zlr22mRY5h4</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/25426-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/25426-1.jpg</snapshot1>			</game>			<game name="Adventure in Serenia (1982)">					<description>Adventure in Serenia (1982)</description>					<rom name="Adventure in Serenia (1982).zip" size="71667"/>							<plot>Despite its title, Adventure Construction Set is an editor that allows players to create their own role-playing scenarios. It is possible to customize a tile-set, maps, and objects to create RPGs reminiscent of the early Ultima games.Seven small 'toolkits' to build from include Sci/Fi, Spy, and Medieval setting templates, plus two complete games are included as a demonstration: Rivers of Light is based on Sumerian mythology and contains 140 rooms and Land of Aventuria consists of seven mini adventures with different settings, e.g. an adaption of Alice in Wonderland or a Nazi castle.</plot>					<genre>Construction and Management SimulationRole-Playing</genre>					<releasedate>01/01/1987</releasedate>					<nplayers>1</nplayers>					<videoid>ZqTr090xsWw</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/19256-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/7/9/1/19791_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/19256-1.jpg</boxart3>			</game>			<game name="Adventureland (1978)">					<description>Adventureland (1978)</description>					<rom name="Adventureland (1978).zip" size="106668"/>					</game>			<game name="Adventures of Alice who Went Through the Looking-Glass and Came Back Though Not Much Changed, The (1986)">					<description>Adventures of Alice who Went Through the Looking-Glass and Came Back Though Not Much Changed, The (1986)</description>					<rom name="Adventures of Alice who Went Through the Looking-Glass and Came Back Though Not Much Changed, The (1986).zip" size="84904"/>							<plot>Richard and Alice are prisoners. Both their cells have a leather sofa and a state-of-the-art computer. But only Richards has a TV.Outside, the snow falls. It has done for some time. Elsewhere, they say, parts of the world have been rendered an inhospitable desert, the earth parched and cracked. People live in the zones now. The lucky ones, anyway.Richard and Alice have secrets.Created by Lewis Denby and Ashton Raze, whose games journalism credits include the likes of Eurogamer, Gamespot and the Telegraph, Richard &amp; Alice is a riveting mystery story about family, desperation and the weather  all set to the beat of an indie adventure game.</plot>					<genre>Adventure</genre>					<releasedate>02/21/2013</releasedate>					<nplayers>1</nplayers>					<videoid>doSnZFbmUAo</videoid>					<fanart1>http://thegamesdb.net/banners/fanart/original/16256-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/16256-1.jpg</boxart1>			</game>			<game name="Adventures of Buckaroo Banzai Across the Eighth Dimension, The (1984)">					<description>Adventures of Buckaroo Banzai Across the Eighth Dimension, The (1984)</description>					<rom name="Adventures of Buckaroo Banzai Across the Eighth Dimension, The (1984).zip" size="91192"/>							<plot>Puzzle Dimension is a 3D puzzle game similar to Kula World where the player needs to roll a ball on a floating structure and collect all flowers to activate a portal that provides the exit. Finding the right path in these puzzles demands a lot of spatial thinking since there are different types of tiles that crumble, ignite or provide no friction and that way retracing your steps is not always possible. The ball can also jump to a skip a tile.Gravity follows the ball - so if it rolls up a slope the entire puzzle will rotate at the same time. This opens up different ways to move in the structures and from the early simple shapes it gets complex later on. It is possible to rotate the view or activate a camera mode where the entire puzzle can be explored. New types of blocks are introduced as the player advances and present new problems and increasingly difficult puzzles to solve. The 100 puzzles are divided into ten clusters, each with their own style and difficulties. The flowers that the player collects are used to unlock more puzzle clusters and to unlock alternative graphical themes. Each of the levels can be played in one of the four available themes as it is only a graphical change. Not all puzzles need to be completed to open up a new cluster as long as a sufficient amount of flowers has been collected.Puzzle Dimension has audiovisuals that blend between a retro and new style. When the player advances through a puzzle graphics change from pixel-blocks to detailed blocks and the music blends from 8-bit retro to new high quality tunes.</plot>					<genre>Role-Playing</genre>					<releasedate>2005</releasedate>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/25512-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/9/5/71595_front.jpg</boxart2>			</game>			<game name="Adventures of Down Under Dan, The (1995)">					<description>Adventures of Down Under Dan, The (1995)</description>					<rom name="Adventures of Down Under Dan, The (1995).zip" size="75420821"/>							<plot>The Adventures of Robin Hood is a video game released in the autumn of 1991 by Millennium Interactive.The protagonist, Robin of Loxley, is robbed of his castle by the Sheriff of Nottingham and has to get it back with the help of Maid Marian, Little John, Will Scarlet and Friar Tuck.The gameplay can be described as an action RPG. The player controls Robin as he robs from the rich to give to the poor, adventures through Sherwood Forest, defeats the sheriff's henchmen, gathers special objects and saves peasants. Heroic acts increase Robin's popularity among NPCs. Archery plays an important role in gameplay.The isometric interface developed for The Adventures of Robin Hood by Millennium Interactive is similar to the interface used in Populous. Robin Hood's interface was later used for Rome: Pathway to Power.Quoted from Wikipedia</plot>					<genre>AdventureRole-PlayingSandbox</genre>					<releasedate>01/01/1999</releasedate>					<nplayers>1</nplayers>					<videoid>xjgQmaZmGl0</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/22712-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/6/2/3/66623_front.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/22712-1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/e/a/5/gfs_65711_1_1.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/4/