<!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_launcher (#PCDATA)>		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>			<emu_name>Sega Genesis</emu_name>			<emu_parser>NoIntro_parser.xml</emu_parser>			<emu_description>No-Intro_Genesis</emu_description>			<emu_category>Sega</emu_category>			<emu_version>08102015</emu_version>			<emu_date>03/03/2015</emu_date>			<emu_author>no-intro</emu_author>			<emu_homepage>http://www.no-intro.org</emu_homepage>			<emu_baseurl>http://archive.org/download/No-Intro-Collection_2015-03-03/Sega%20-%20Mega%20Drive%20-%20Genesis.zip/Sega%20-%20Mega%20Drive%20-%20Genesis%2F</emu_baseurl>			<emu_launcher>retroplayer</emu_launcher>			<emu_ext_launch_cmd>none</emu_ext_launch_cmd>			<emu_downloadpath>default</emu_downloadpath>			<emu_postdlaction>none</emu_postdlaction>			<emu_comment>No Intro Genesis List by Zach Morris, removed all beta, and Non-USA games.The Sega Genesis is a fourth-generation video game console developed and produced by Sega. It was originally released in Japan in 1988 as Mega Drive, then in North America in 1989 as Sega Genesis, and in Europe, Australia and other PAL regions in 1990 as Mega Drive. The reason for the two names is that Sega was unable to secure legal rights to the Mega Drive name in North America. The Sega Genesis is Sega's third console and the successor to the Sega Master System with which it has backward compatibility. The controversy over games like Mortal Kombat in the United States forced Sega to create the first content rating system for video games, the Videogame Rating Council, rather than have the games heavily censored. The rating system allowed Sega to ship games with little to no censorship and gave it a competive edge when the same game was released by Nintendo. The success of those games eventually forced Nintendo to join its rating system.Developer:  SegaManufacturer:  SegaCPU:  Motorola 68000Memory:  64K work RAM (68000), 64K video RAM, 8K work RAM (Z80)Graphics:  Yamaha YM7101Sound:  Yamaha YM2612 5 channel FM and 1 channel FM/PCM, Texas Instruments SN76489 4 channel PSG (Programmable Sound Generator)Display:  320Ã—448Media:  CartridgeMax. Controllers:  2</emu_comment>			<emu_thumb>http://thegamesdb.net/banners/platform/boxart/18-1.jpg</emu_thumb>			<emu_banner>http://thegamesdb.net/banners/platform/banners/18-1.png</emu_banner>			<emu_fanart>http://upload.wikimedia.org/wikipedia/commons/6/6a/Sega-Genesis-Mk2-6button.jpg</emu_fanart>			<emu_logo>http://upload.wikimedia.org/wikipedia/en/1/12/GenesisLogo.png</emu_logo>			<emu_trailer>ALG9JQGrECA</emu_trailer>		</header>			<game name="3 Ninjas Kick Back (USA)">					<description>3 Ninjas Kick Back (USA)</description>					<rom crc="e5a24999" name="3 Ninjas Kick Back (USA).zip" size="2097152"/>					<videoid>EpatpehwS6E</videoid>					<plot>3 Ninjas Kick Back follows 3 young ninja  brothers, Rocky, Colt and Tum-Tum as they assist an old Samurai in retrieving a prized dagger which has been stolen by his rival. The dagger, once given to the Samurai as a reward, will be passed along to younger generations once it is restored to its rightful owner. The boys learn ninjitsu and karate as they fight evil forces that are older, more powerful, and bigger than them.</plot>					<genre>Action</genre>					<nplayers>2</nplayers>					<studio>Sony Imagesoft</studio>					<releasedate>06/01/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/3371-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/3371-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/3371-2.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/3371-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/3371-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/3371-3.jpg</snapshot3>					<snapshot4>http://thegamesdb.net/banners/screenshots/3371-4.jpg</snapshot4>					<snapshot5>http://thegamesdb.net/banners/screenshots/3371-5.jpg</snapshot5>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/3371.png</clearlogo1>			</game>			<game name="6-Pak (USA)">					<description>6-Pak (USA)</description>					<rom crc="1a6f45dc" name="6-Pak (USA).zip" size="3145728"/>					<fanart1>http://thegamesdb.net/banners/fanart/original/3371-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/3371-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/3371-2.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/3371-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/3371-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/3371-3.jpg</snapshot3>					<snapshot4>http://thegamesdb.net/banners/screenshots/3371-4.jpg</snapshot4>					<snapshot5>http://thegamesdb.net/banners/screenshots/3371-5.jpg</snapshot5>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/3371.png</clearlogo1>			</game>			<game name="688 Attack Sub (USA, Europe)">					<description>688 Attack Sub (USA, Europe)</description>					<rom crc="f2c58bf7" name="688 Attack Sub (USA, Europe).zip" size="1048576"/>					<videoid>onufRqtnnOM</videoid>					<plot>An early submarine game with ten missions which can be played with both American and Soviet attack submarines. The game focuses on realism with several stations the player can use (sonar, weapons, navigation, helm, radio and periscope) but most duties can be delegated to crew members. The graphics are mostly close-up views of the control panels but in some occasions they feature digitized images of surface ships and crew.</plot>					<genre>Strategy</genre>					<nplayers>1</nplayers>					<studio>SEGA Enterprises Ltd.</studio>					<releasedate>01/01/1991</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/3863-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/3863-2.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/3863-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/3863-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/3863-3.jpg</snapshot3>					<snapshot4>http://thegamesdb.net/banners/screenshots/3863-4.jpg</snapshot4>					<snapshot5>http://thegamesdb.net/banners/screenshots/3863-5.jpg</snapshot5>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/3863.png</clearlogo1>			</game>			<game name="Aaahh!!! Real Monsters (USA)">					<description>Aaahh!!! Real Monsters (USA)</description>					<rom crc="fdc80bfc" name="Aaahh!!! Real Monsters (USA).zip" size="2097152"/>					<videoid>xIr3w005iro</videoid>					<plot>In this game, based on popular Nickelodeon comics, you control three monsters: Ickis, Oblina, and Krumm. The Gromble, a headmaster in monster school, needs you to perform the final test - monster Midterm Exam - in order to prove yourselves to be real monsters. You should collect trash, throw it on people, and scare them!This is a platform game, where you control three characters. Each one of them has a special move that is often used to solve puzzles and overcome obstacles: Ickis can fly for a short time, Oblina can reach high ledges, and Krumm can scan off-screen areas. They can also collect monster books, that will teach them to scare people. Help the three monsters to graduate!</plot>					<genre>Platform</genre>					<studio>Viacom</studio>					<releasedate>09/15/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/4184-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4184-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4184-1.png</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4184.png</clearlogo1>			</game>			<game name="Aaahh!!! Real Monsters (USA) (Beta) (1995-07-07)">					<description>Aaahh!!! Real Monsters (USA) (Beta) (1995-07-07)</description>					<rom crc="f4b44b82" name="Aaahh!!! Real Monsters (USA) (Beta) (1995-07-07).zip" size="2097152"/>					<videoid>xIr3w005iro</videoid>					<plot>In this game, based on popular Nickelodeon comics, you control three monsters: Ickis, Oblina, and Krumm. The Gromble, a headmaster in monster school, needs you to perform the final test - monster Midterm Exam - in order to prove yourselves to be real monsters. You should collect trash, throw it on people, and scare them!This is a platform game, where you control three characters. Each one of them has a special move that is often used to solve puzzles and overcome obstacles: Ickis can fly for a short time, Oblina can reach high ledges, and Krumm can scan off-screen areas. They can also collect monster books, that will teach them to scare people. Help the three monsters to graduate!</plot>					<genre>Platform</genre>					<studio>Viacom</studio>					<releasedate>09/15/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/4184-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4184-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4184-1.png</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4184.png</clearlogo1>			</game>			<game name="Addams Family, The (USA) (Beta)">					<description>Addams Family, The (USA) (Beta)</description>					<rom crc="2803a5ca" name="Addams Family, The (USA) (Beta).zip" size="1048576"/>					<videoid>UriKl2OtjKw</videoid>					<plot>Loosely based on the plot of the film, the player takes the role of Uncle Fester as he searches for the recently kidnapped baby Pubert. On the way he receives help from The Addams Family and a host of original characters from the game.</plot>					<genre>ActionRole-Playing</genre>					<nplayers>1</nplayers>					<studio>Ocean Software</studio>					<releasedate>12/06/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/9414-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9414-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9414-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/9414-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/9414.png</clearlogo1>			</game>			<game name="Addams Family, The (USA) (Beta) (Alt 1)">					<description>Addams Family, The (USA) (Beta) (Alt 1)</description>					<rom crc="3a173e1f" name="Addams Family, The (USA) (Beta) (Alt 1).zip" size="1048576"/>					<videoid>UriKl2OtjKw</videoid>					<plot>Loosely based on the plot of the film, the player takes the role of Uncle Fester as he searches for the recently kidnapped baby Pubert. On the way he receives help from The Addams Family and a host of original characters from the game.</plot>					<genre>ActionRole-Playing</genre>					<nplayers>1</nplayers>					<studio>Ocean Software</studio>					<releasedate>12/06/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/9414-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9414-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9414-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/9414-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/9414.png</clearlogo1>			</game>			<game name="Addams Family, The (USA, Europe)">					<description>Addams Family, The (USA, Europe)</description>					<rom crc="71f58614" name="Addams Family, The (USA, Europe).zip" size="1048576"/>					<videoid>UriKl2OtjKw</videoid>					<plot>Loosely based on the plot of the film, the player takes the role of Uncle Fester as he searches for the recently kidnapped baby Pubert. On the way he receives help from The Addams Family and a host of original characters from the game.</plot>					<genre>ActionRole-Playing</genre>					<nplayers>1</nplayers>					<studio>Ocean Software</studio>					<releasedate>12/06/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/9414-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9414-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9414-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/9414-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/9414.png</clearlogo1>			</game>			<game name="Adventures of Batman &amp; Robin, The (USA)">					<description>Adventures of Batman &amp; Robin, The (USA)</description>					<rom crc="0caaa4ac" name="Adventures of Batman &amp; Robin, The (USA).zip" size="2097152"/>					<videoid>8bWAwSRQ7fA</videoid>					<plot>The Mega Drive/Genesis version, developed by Clockwork Tortoise and published by Sega, is a run 'n' gun where both Batman and Robin must stop Mr. Freeze, who plans to freeze Gotham City. In order to keep the duo busy, he also frees the Joker, Two-Face and the Mad Hatter, each one with their own agenda. The Joker celebrates his birthday wreaking havoc in Gotham and stealing diamonds, Two-Face tries to take over the city from above, and Mad Hatter is creating a robot army in his surreal lair.The game can be played by two players simultaneously; one player with Batman, and the other with Robin. Both characters are identical in terms of playability, and both use batarangs, bolas, or shirukens in long-range attacks, while using melee attacks at short range. There are four levels consisting of several stages, mostly of a straight left-to-right traverse to the end where the boss awaits. In some levels the game switches to a side-scrolling shooter, in which the players must control the Batwings.The game is regarded as being extremely difficult to complete, and also known for showcasing some of the most impressive special effects on the Mega Drive/Genesis. It also features a soundtrack by Jesper Kyd. This accounts for the relatively high quality of Kyd's compositions, as well as the fairly simple FM synthesized nature of the game's sound effects.</plot>					<genre>Action</genre>					<nplayers>2</nplayers>					<studio>Sega</studio>					<releasedate>02/10/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/9415-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/9415-2.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9415-2.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/9415-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/9415-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/9415.png</clearlogo1>			</game>			<game name="Adventures of Mighty Max, The (USA)">					<description>Adventures of Mighty Max, The (USA)</description>					<rom crc="55f13a00" name="Adventures of Mighty Max, The (USA).zip" size="1048576"/>					<plot>Max is a kid who possesses a magic cap that allows you to travel across different world and to save people who get in trouble in other dimensions. But his archenemy, the demonic Skull Master, has recently locked all the portals Max was using for inter-dimensional travel. However, the Skull Master has kept some of the portals for himself, keeping there some of his destructive weapons. It's time to destroy those weapons and to stop Skull Master!</plot>					<genre>ActionPlatform</genre>					<studio>Ocean</studio>					<releasedate>01/01/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/4235-1.jpg</boxart2>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4235.png</clearlogo1>			</game>			<game name="Adventures of Rocky and Bullwinkle and Friends, The (USA)">					<description>Adventures of Rocky and Bullwinkle and Friends, The (USA)</description>					<rom crc="ef02d57b" name="Adventures of Rocky and Bullwinkle and Friends, The (USA).zip" size="1048576"/>					<plot>The Adventures of Rocky and Bullwinkle is the video game adaptation of the 60's cartoon series staring Bullwinkle, a moose, and Rocky, a flying squirrel. The game plays out much like an episode of the show. The story begins at the dedication of the Frostbite Falls Rocky and Bullwinkle museum. Unfortunately, the not-so-nice Boris and Natasha have disguised themselves as security guards for the museum and managed to steal some of the priceless artifacts.</plot>					<genre>Platform</genre>					<studio>Absolute Entertainment</studio>					<releasedate>01/01/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/4234-1.jpg</boxart2>			</game>			<game name="Aero the Acro-Bat (USA)">					<description>Aero the Acro-Bat (USA)</description>					<rom crc="a3a7a8b5" name="Aero the Acro-Bat (USA).zip" size="1048576"/>					<plot>You play as bat Aero, who have to stop the mad scientist Edgar Ektor, who is trying to rid the world of amusement and fun. So you jump through the circus-style levels, using different kinds of machines such as catapults, cannons, bubble machines, platforms, etc., collecting various power-ups such as cheese, soda, keys, clocks, etc. and avoiding lethal obstacles.</plot>					<genre>ActionPlatform</genre>					<nplayers>1</nplayers>					<studio>Sunsoft</studio>					<releasedate>01/01/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/4237-1.png</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4237-2.png</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/4237-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/4237-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/4237-3.jpg</snapshot3>					<snapshot4>http://thegamesdb.net/banners/screenshots/4237-4.jpg</snapshot4>					<snapshot5>http://thegamesdb.net/banners/screenshots/4237-5.jpg</snapshot5>					<snapshot6>http://thegamesdb.net/banners/screenshots/4237-6.jpg</snapshot6>					<snapshot7>http://thegamesdb.net/banners/screenshots/4237-7.jpg</snapshot7>					<snapshot8>http://thegamesdb.net/banners/screenshots/4237-8.jpg</snapshot8>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4237.png</clearlogo1>			</game>			<game name="Aero the Acro-Bat 2 (USA)">					<description>Aero the Acro-Bat 2 (USA)</description>					<rom crc="39eb74eb" name="Aero the Acro-Bat 2 (USA).zip" size="2097152"/>					<plot>In the sequel to Aero the Acro-Bat you have to defeat evil industrialist Edgar Ektor once again. He is back and again with bad ideas, so you - in the role of Aero - have to find and destroy him before he carries out his diabolical &quot;Plan B&quot;. Like in the last installment, you have to jump, escape lethal obstacles and progress in time. This game features more moves for Aero, more mechanisms to use and more items to collect.</plot>					<genre>Platform</genre>					<studio>Sunsoft</studio>					<releasedate>01/01/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/4238-1.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/4238-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/4238-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/4238-3.jpg</snapshot3>					<snapshot4>http://thegamesdb.net/banners/screenshots/4238-4.jpg</snapshot4>					<snapshot5>http://thegamesdb.net/banners/screenshots/4238-5.jpg</snapshot5>					<snapshot6>http://thegamesdb.net/banners/screenshots/4238-6.jpg</snapshot6>					<snapshot7>http://thegamesdb.net/banners/screenshots/4238-7.jpg</snapshot7>					<snapshot8>http://thegamesdb.net/banners/screenshots/4238-8.jpg</snapshot8>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4238.png</clearlogo1>			</game>			<game name="Aerobiz (USA)">					<description>Aerobiz (USA)</description>					<rom crc="cfaa9bce" name="Aerobiz (USA).zip" size="1048576"/>					<plot>You are the CEO of an airline company. Your goal is to become the most successful airline in the world by connecting all 22 cities with air routes, maintain a profit, and meet the required quota of passengers. If you cannot turn a profit for a year or meet the victory conditions in 32 years you lose. Some strategic decisions you must make include negotiating for open air routes, purchasing or selling aircraft, invest in branch offices and hotels, advertise your airline and set budgets. You must also pay attention to statistics like quarterly and annual sales reports, as well as city data. World events also affect your airline, from natural disasters to war and even the Olympic games, all of which will affect how many passengers you get. All the planes in the game are based on real-life aircraft, such as the Boeing 747 and the Concorde.</plot>					<genre>Strategy</genre>					<studio>Koei</studio>					<releasedate>01/01/1992</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/4239-1.jpg</boxart2>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/4239.png</clearlogo1>			</game>			<game name="Aerobiz Supersonic (USA)">					<description>Aerobiz Supersonic (USA)</description>					<rom crc="9377f1b5" name="Aerobiz Supersonic (USA).zip" size="1048576"/>					<plot>You have just been elected as the CEO of a brand new airline company that must compete against 3 other airlines for global dominance. Set up new routes, buy businesses, and manage all your resources including planes, cashflow, and company representatives.</plot>					<genre>Life Simulation</genre>					<nplayers>4+</nplayers>					<studio>Koei</studio>					<releasedate>04/02/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/447-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/447-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/447.png</clearlogo1>			</game>			<game name="After Burner II (USA, Europe)">					<description>After Burner II (USA, Europe)</description>					<rom crc="ccafe00e" name="After Burner II (USA, Europe).zip" size="524288"/>					<plot>Similar to its predecessor, the premise of After Burner II is to get on the F-14 Tomcat and fly mission after mission of shooting planes out of the sky. At your disposal is a vulcan cannon (basically a machine gun) and a limited number of missiles. In some versions of the game the guns fire automatically all the time. Sometimes you come across a friendly supply plane and if you dock with it you can replenish your missiles.The game is viewed from behind the plane with you fighting wave after wave of enemy fighters. But at heart it offers the usual shooter mechanics, meaning you spend most of your time dodging and shooting. You also can speed up and slow down to deal with enemies which appear behind you.</plot>					<genre>Shooter</genre>					<nplayers>1</nplayers>					<studio>Sega</studio>					<releasedate>07/15/1990</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/446-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/446-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/446-1.jpg</boxart1>					<banner1>http://thegamesdb.net/banners/graphical/446-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/446.png</clearlogo1>					<videoid>AcaXbr6l-54</videoid>			</game>			<game name="Air Buster (USA)">					<description>Air Buster (USA)</description>					<rom crc="f3d65baa" name="Air Buster (USA).zip" size="524288"/>					<videoid>X_yhkTs9nz0</videoid>					<plot>This isn't a little skirmish in the air. This is a full-fledged, take-no-prisoners, hyper-drive war to the finish with three-dimensional screens and incredible sound effects. Simultaneous two-player action with horizontal and vertical scrolling means you need cunning, instinct, and flight skills to destroy the enemy...and survive!</plot>					<genre>ActionShooter</genre>					<studio>Kaneko</studio>					<releasedate>01/31/1991</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/3864-1.jpg</boxart2>					<banner1>http://thegamesdb.net/banners/graphical/3864-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/3864.png</clearlogo1>			</game>			<game name="Air Diver (USA)">					<description>Air Diver (USA)</description>					<rom crc="2041885e" name="Air Diver (USA).zip" size="524288"/>					<plot>Your mission is to find and eliminate the enemy terrorists. They are extremely well armed, and central intelligence informs us that they may have the backing of several unfriendly extraterrestrial nations...</plot>					<genre>ActionShooter</genre>					<nplayers>1</nplayers>					<studio>Seismic</studio>					<releasedate>04/01/1990</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/448-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/448-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/448.png</clearlogo1>			</game>			<game name="Aladdin (USA) (Beta)">					<description>Aladdin (USA) (Beta)</description>					<rom crc="8c60ef73" name="Aladdin (USA) (Beta).zip" size="2097152"/>					<plot>The game involves killing enemies with basic swordplay and jumping across ledges. There are several levels, including one level where Aladdin must escape from the Cave of Wonders on Carpet and another where he must jump across the Agrabah's rooftops.The player controls Aladdin, who must make his way through several levels based on locations from the movie: from the streets and rooftops of Agrabah, the Cave of Wonders and the Sultan's dungeon to the final confrontation in Grand Vizier Jafar's palace. The Sultan's guards and also animals of the desert want to hinder Aladdin in his way. He can defend himself with his sword or by throwing apples. Next to apples, Aladdin can also collect gems which can be traded for lives and continues with a traveling trader. Finding Genie or Abu icons enables bonus rounds. The Genie bonus round is a game of luck played for apples, gems or extra lives, and continues until the player runs out of Genie tokens or lands on Jafar. In Abu's bonus round, the player controls the little monkey who has to catch bonus items that fall from the sky, but without touching any of the unwanted objects like rocks and pots.</plot>					<genre>Action</