<?xml version="1.0" ?><!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart20 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>			<emu_name>Nintendo 64 - N64</emu_name>			<emu_parser>NoIntro_parser.xml</emu_parser>			<emu_description>No-Intro N64</emu_description>			<emu_category>Nintendo</emu_category>			<emu_version>20150417-171920</emu_version>			<emu_date>04/17/2015</emu_date>			<emu_author>no-intro</emu_author>			<emu_homepage>http://www.no-intro.org</emu_homepage>			<emu_baseurl>http://archive.org/download/No-Intro-Collection_2015-03-03/Nintendo%20-%20Nintendo%2064.zip/Nintendo%20-%20Nintendo%2064%2F</emu_baseurl>			<emu_downloadpath>default</emu_downloadpath>			<emu_postdlaction>None</emu_postdlaction>			<emu_comment>No Intro N64 List by Zach Morris, removed all beta, and Non-USA games.Often referred to as N64, was Nintendo′s third home video game console for the international market. Named for its 64-bit CPU, it was released in June 1996 in Japan, September 1996 in North America, March 1997 in Europe and Australia, September 1997 in France and December 1997 in Brazil. It is Nintendo′s last home console to use ROM cartridges to store games (Nintendo switched to a MiniDVD-based format for the successor GameCube); handhelds in the Game Boy line, however, continued to use Game Paks. It was discontinued in 2001 in Japan, North America and PAL regions by the launch of Nintendo′s GameCube.Developer:  NintendoManufacturer:  NintendoCPU:  93.75 MHz NEC VR4300Memory:  4MB RDRAMGraphics:  62.5 MHz SGI RCPSound:  48 kHz with 16-bit audioDisplay:  480iMedia:  CartridgeMax. Controllers:  4			</emu_comment>			<emu_thumb>http://thegamesdb.net/banners/platform/boxart/3-1.jpg</emu_thumb>			<emu_banner>http://thegamesdb.net/banners/platform/banners/3-2.jpg</emu_banner>			<emu_fanart>http://upload.wikimedia.org/wikipedia/commons/e/e9/Nintendo-64-wController-L.jpg</emu_fanart>			<emu_logo>http://upload.wikimedia.org/wikipedia/en/thumb/0/04/Nintendo_64_Logo.svg/1106px-Nintendo_64_Logo.svg.png</emu_logo>			<emu_trailer>VcwDHrhqHP0</emu_trailer>		</header>			<game name="007 - GoldenEye (USA)">					<description>007 - GoldenEye (USA)</description>					<rom crc="8b70cb5b" name="007 - GoldenEye (USA).zip" sha1="7DD376E996D77D108316AC7CED087125C5674FA4" size="12582912"/>					<videoid>a4qJ8wNfgXY</videoid>					<plot>You are Bond, James Bond.You are assigned to covert operations connected with the GoldenEye weapons satellite.  M will brief you on your mission and objectives from London.  Q Branch will support your efforts with a plentiful supply of weapons and gadgets.  Moneypenny offers you light-hearted best wishes and youre off!Your mission begins in the heavily guarded chemical warfare facility at the Byelomorye Dam in the USSR.  Look and shoot in any direction as you navigate 12 interactive 3-D environments.  Use stealth and force as you see fit in matters of international security.  Consider the military personnel expendable.  You are licensed to kill!* Exciting 3-D environments.* Highly intelligent enemies!* Numerous Q gadgets and weapons!* Battery-backed memory saves game progress!</plot>					<genre>Shooter</genre>					<nplayers>4+</nplayers>					<studio>Nintendo</studio>					<releasedate>08/23/1997</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/160-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/160-2.jpg</fanart2>					<fanart3>http://thegamesdb.net/banners/fanart/original/160-3.jpg</fanart3>					<fanart4>http://thegamesdb.net/banners/fanart/original/160-4.jpg</fanart4>					<fanart5>http://thegamesdb.net/banners/fanart/original/160-5.jpg</fanart5>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/160-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/160-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/160-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/160-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/160-3.jpg</snapshot3>					<banner1>http://thegamesdb.net/banners/graphical/160-g.jpg</banner1>					<banner2>http://thegamesdb.net/banners/graphical/160-g2.jpg</banner2>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/160.png</clearlogo1>			</game>			<game name="007 - The World Is Not Enough (USA)">					<description>007 - The World Is Not Enough (USA)</description>					<rom crc="34f0ee5b" name="007 - The World Is Not Enough (USA).zip" sha1="E93005466AC84BC1D19B40673D0C50B604A8753C" size="33554432"/>					<videoid>-i9Pz6IzBgw</videoid>					<plot>007:The World Is Not Enough was released in 2000 as a video game adaption of the same-titled movie and a successor to GoldenEye 007. The storyline generally follows the movie plot, whereas James Bond has to protect Elektra King from a terrorist called Renard; but as it surprisingly turns out that King is working together with Renard to blow up Istanbul with a nuclear submarine in order to take over the World's oil market, Bond teams up with Dr. Christmas Jones to stop their plans. The N64 version features 14 Levels in the Single-Player campaign as well as Multiplayer Modes with 4-Player Support &amp; additional AI bots.</plot>					<genre>ActionShooter</genre>					<nplayers>4+</nplayers>					<studio>Nintendo</studio>					<releasedate>10/17/2000</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/238-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/238-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/238-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/238-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/238-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/238.png</clearlogo1>			</game>			<game name="1080 TenEighty Snowboarding (Japan, USA) (En,Ja)">					<description>1080 TenEighty Snowboarding (Japan, USA) (En,Ja)</description>					<rom crc="d1744951" name="1080 TenEighty Snowboarding (Japan, USA) (En,Ja).zip" sha1="5F837C13A2FB3C8CDFD6FB720BD4A963AB515632" size="16777216" status="verified"/>					<videoid>8hAWCad3IS8</videoid>					<plot>Youre taking a Tahoe 155 snowboard down a steep, bumpy incline at night and youre about to top off an Indy Nosebone with a 360 Air, and you havent even left your living room!  Youre Playing 1080 (Ten Eighty) Snowboarding, a game so intense youll be brushing the snow off your goggles.  With five different boarders, eight different Lamar snowboards, more than 25 tricks, a Half-Pipe and six different courses, this is as close as youll get to the real thing without hopping on the next ski life.* Six game modes and courses!* 2-Player simultaneous play!* Over 25 different tricks!* Compatible with Rumble Pak accessory.</plot>					<genre>Sports</genre>					<nplayers>2</nplayers>					<studio>Nintendo</studio>					<releasedate>04/01/1998</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/237-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/237-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/237-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/237-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/237-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/237-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/237-3.jpg</snapshot3>					<snapshot4>http://thegamesdb.net/banners/screenshots/237-4.jpg</snapshot4>					<snapshot5>http://thegamesdb.net/banners/screenshots/237-5.jpg</snapshot5>					<snapshot6>http://thegamesdb.net/banners/screenshots/237-6.jpg</snapshot6>					<banner1>http://thegamesdb.net/banners/graphical/237-g.jpg</banner1>					<banner2>http://thegamesdb.net/banners/graphical/237-g2.jpg</banner2>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/237.png</clearlogo1>			</game>			<game name="AeroFighters Assault (USA)">					<description>AeroFighters Assault (USA)</description>					<rom crc="b08ef0b9" name="AeroFighters Assault (USA).zip" sha1="DE542F002E4F08CFDAC19DEC57F5BBAEA6EDEAFE" size="8388608"/>					<videoid>XxIMhSo1sz8</videoid>					<plot>The Aero Fighters Assault team needs your help to save the Earth from the evil Phutta Morgana organization and their machines of doom. Join the battle and choose your fighter from 6 different aircrafts with unique missiles and special weapons to wipe out your enemies in 3D-environment!</plot>					<genre>ActionFlight Simulator</genre>					<nplayers>2</nplayers>					<studio>Video System</studio>					<releasedate>11/01/1997</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1052-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1052-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1052-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1052-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1052.png</clearlogo1>			</game>			<game name="AeroGauge (USA)">					<description>AeroGauge (USA)</description>					<rom crc="04038cb8" name="AeroGauge (USA).zip" sha1="204DF59CBD065E39CADCCC23A68E08AE212546D0" size="8388608"/>					<videoid>9GviRk0cIm0</videoid>					<plot>In the tradition of F-Zero and Wipeout, AeroGauge is a sci-fi racer that pits you and a friend in a fast paced race to the finish through futuristic tracks and among detailed craft, acting more like planes than racers as they skim many metres above the ground. Play solo through the grand prix and compete against the AI enemy, or beat down your best time in the time trial mode. Each track features a number of twists and turns, whether it be racing upside down or vertically, with a number of obstacles in your path. There's no weapons, though, it's just you and the open road ahead.</plot>					<genre>Racing</genre>					<nplayers>2</nplayers>					<studio>ASCII Entertainment Software</studio>					<releasedate>03/30/1998</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1053-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1053-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1053-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1053-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1053-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1053.png</clearlogo1>			</game>			<game name="Aidyn Chronicles - The First Mage (USA) (Rev A)">					<description>Aidyn Chronicles - The First Mage (USA) (Rev A)</description>					<rom crc="276178df" name="Aidyn Chronicles - The First Mage (USA) (Rev A).zip" sha1="C4D93DA5205EDCAD44177A26E32532D98795FA3E" size="33554432"/>					<plot>Aidyn Chronicles: The First Mage follows the story of Alaron, who is poisoned by goblins while searching for a missing farmer named Kendallon in King Loyd's kingdom. Without a common cure, Alaron must set out on a journey with a selection of companions in search of the antidote. After some time Alaron realizes that he is more than an ordinary young man and that his journey is more dangerous than he first thought. Mysterious evil forces are brewing in the distance and lurking in every dark corner - can Alaron find &amp; fulfill his true fate?</plot>					<genre>Role-Playing</genre>					<nplayers>1</nplayers>					<studio>THQ</studio>					<releasedate>03/14/2001</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1054-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1054-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1054-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1054-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1054.png</clearlogo1>			</game>			<game name="Aidyn Chronicles - The First Mage (USA)">					<description>Aidyn Chronicles - The First Mage (USA)</description>					<rom crc="8da62304" name="Aidyn Chronicles - The First Mage (USA).zip" sha1="32EF42E143B74CB957A88DDB9249AF13B15B45E7" size="33554432"/>					<plot>Aidyn Chronicles: The First Mage follows the story of Alaron, who is poisoned by goblins while searching for a missing farmer named Kendallon in King Loyd's kingdom. Without a common cure, Alaron must set out on a journey with a selection of companions in search of the antidote. After some time Alaron realizes that he is more than an ordinary young man and that his journey is more dangerous than he first thought. Mysterious evil forces are brewing in the distance and lurking in every dark corner - can Alaron find &amp; fulfill his true fate?</plot>					<genre>Role-Playing</genre>					<nplayers>1</nplayers>					<studio>THQ</studio>					<releasedate>03/14/2001</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1054-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1054-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1054-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1054-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1054.png</clearlogo1>			</game>			<game name="All Star Tennis 99 (USA)">					<description>All Star Tennis 99 (USA)</description>					<rom crc="7326e6c9" name="All Star Tennis 99 (USA).zip" sha1="2655AF06374C3CA9F8A40A76F7F9FC6E1044B576" size="8388608"/>					<videoid>dYMofRW1VZ4</videoid>					<plot>Play as 8 world class ATP / WTA tour players (including Mark Philippoussis, Richard Krajicek, Conchita Martinez &amp; Jana Novotna) as well as 4 fictional players through a range of tournaments on grass, clay, hard court and rebound ace surfaces.Lob, volley, smash and serve past computer controlled players in singles or doubles, 4 player multiplayer doubles, and 8 player multiplayer singles and doubles tournaments.</plot>					<genre>Sports</genre>					<nplayers>4+</nplayers>					<studio>Ubisoft</studio>					<releasedate>08/31/1999</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1056-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1056-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1056-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1056-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1056-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1056.png</clearlogo1>			</game>			<game name="All-Star Baseball 2000 (USA)">					<description>All-Star Baseball 2000 (USA)</description>					<rom crc="15063eac" name="All-Star Baseball 2000 (USA).zip" sha1="C0D574AF5C3523A4A804182B4D6465212FD9EE29" size="16777216"/>					<plot>All-Star Baseball 2000 is the second release in the series and includes a range of improvements and new features compared to the '99 version. Motion captured technology allows a realistic representation of player movements, swings, throws and catches. Apart from the improved roster management, which includes the ability to sign players from the minor league and create new players with new stats, you are able to play a 162 game inter-league season or complete the 1999 MLB scheduled season.Once more there are 30 teams available in the game, as well as home stadiums and home or away jerseys. Additionally players' face sizes and play styles coincide with the real ones, since the game is licensed.</plot>					<genre>Sports</genre>					<nplayers>4+</nplayers>					<studio>Acclaim</studio>					<releasedate>03/31/1999</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1058-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1058-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1058-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1058-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1058.png</clearlogo1>			</game>			<game name="All-Star Baseball 2001 (USA)">					<description>All-Star Baseball 2001 (USA)</description>					<rom crc="3e8be0e0" name="All-Star Baseball 2001 (USA).zip" sha1="353AD679666287988A0E645851EE01EFF2048449" size="16777216"/>					<plot>The last All-Star Baseball release on the N64 once again includes some new features as well as improvements in relation to previous play modes &amp; options. For 2001, a new team is included, The Coopertown Legends, featuring a selection of some of the finest players to ever grace the MLB, including Yogi Berra, Willie Stargell and Reggie Jackson.Along with the legends team, you can choose from every player, team and stadium from the real 2000 MLB season. Each player includes facial expressions and looks inspired to realism, plus motion-captured player movements, batting stances and reactions to key events during play.</plot>					<genre>Sports</genre>					<nplayers>4+</nplayers>					<studio>Acclaim</studio>					<releasedate>02/29/2000</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1059-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1059-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1059-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1059-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1059.png</clearlogo1>			</game>			<game name="All-Star Baseball 99 (USA)">					<description>All-Star Baseball 99 (USA)</description>					<rom crc="82b7e47d" name="All-Star Baseball 99 (USA).zip" sha1="6D01A4986311A4486B4B0BE029658E8DF63F4EE4" size="12582912"/>					<plot>All-Star Baseball is a baseball video game series developed and published by Acclaim Entertainment. The series began in 1998 with the release of All-Star Baseball '99. All 30 Major League Baseball teams feature in the first All-Star Baseball title. Game modes include Training, Season, Playoff, World Series, plus an All-Star Match, Home Run Derby and MLB trivia. 100 different batting styles are featured, as well as motions such as sliding catches, base collisions, kneeling throws and broken bats. It's also possible to sign up and trade players from all around the league and creating your own team from the entire 700-player roster. And if a player fitting your demands doesn't exist, you can use the Create a Player mode for further versatility.</plot>					<genre>Sports</genre>					<nplayers>4+</nplayers>					<studio>Acclaim</studio>					<releasedate>04/30/1998</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1057-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1057-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1057-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1057-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1057.png</clearlogo1>			</game>			<game name="Armorines - Project S.W.A.R.M. (USA)">					<description>Armorines - Project S.W.A.R.M. (USA)</description>					<rom crc="950985f6" name="Armorines - Project S.W.A.R.M. (USA).zip" sha1="A9C1319C582668B9AFC7807DCD59F68D09B5317E" size="16777216"/>					<plot>The invasion has begun - an alien species infestated Earth and now they are after your flesh! Choose one of two Armorines, each with their own selection of weapons and fight back against bugs of all sizes; minimize the enemies chance of eliminating human civilization as we know it and eradicate every single trace of their race on our beloved planet!</plot>					<genre>ActionShooter</genre>					<nplayers>4+</nplayers>					<studio>Acclaim</studio>					<releasedate>12/02/1999</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1060-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1060-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1060-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1060-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1060-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1060-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1060.png</clearlogo1>			</game>			<game name="Army Men - Air Combat (USA)">					<description>Army Men - Air Combat (USA)</description>					<rom crc="2355e4f3" name="Army Men - Air Combat (USA).zip" sha1="52F4722CBF3DED8E55A62471FBC5A6CF07F4FD5D" size="8388608"/>					<videoid>KbqtijaifBU</videoid>					<plot>3DO's Army Men franchise hits a higher level again with Army Men: Air Combat! As Captain William Blade, the toy pilot of several plastic toy helicopters, you are battling with the evil tan army and their terrifying war machines. Real-world settings include backyard, playgrounds, campgrounds and giant sandcastles, spread out over 16 single player missions and competitive multiplayer modes. For your battles, four types of helicopters are available (Chinook, Apache, Huey and Super Stallion) to fight enemies like toy robots, electric trains, killer bees and dragonflies. In addition, interactions with your environment are also possible; pick up dog dishes, soda cans, doughnuts or bags of fertilizer for use against the evil tan toys and wipe them out!</plot>					<genre>Action</genre>					<nplayers>4+</nplayers>					<studio>3DO</studio>					<releasedate>07/24/2000</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/2535-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/2535-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/2535-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/2535-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/2535-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/2535.png</clearlogo1>			</game>			<game name="Army Men - Sarge's Heroes (USA)">					<description>Army Men - Sarge's Heroes (USA)</description>					<rom crc="97bf6db2" name="Army Men - Sarge's Heroes (USA).zip" sha1="82F8D41D16C9161FF21776A8B2531CB11857F410" size="8388608"/>					<videoid>V5IbVO1MUbc</videoid>					<plot>In Army Men: Sarge's Heroes you play as Sarge, the protagonist from many of the Army Men games. Tan Army is invading the Green Army base; Sarge rescues Colonel Grimm and they evacuate the base in a helicopter. Sarge discovers portals that lead from the &quot;plastic world&quot; to the &quot;real world&quot; and that the Tan Army is trying to acquire &quot;Weapons of Mass Destruction&quot; from the &quot;real world&quot; , for example toys and ordinary objects like magnifying glass. To avoid the destruction of the Green Army, Sarge has to rescue commandos of his own unit, Bravo Company, to destroy vehicles &amp; portals and finally stop the evil general Plastro.</plot>					<genre>ActionShooter</genre>					<nplayers>2</nplayers>					<studio>3DO</studio>					<releasedate>11/16/2000</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/240-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/240-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/240-2.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/240-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/240-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/240.png</clearlogo1>			</game>			<game name="Army Men - Sarge's Heroes 2 (USA)">					<description>Army Men - Sarge's Heroes 2 (USA)</description>					<rom crc="3e9d1c51" name="Army Men - Sarge's Heroes 2 (USA).zip" sha1="FF1A799C6C0AEC45EFA7E0F8D107D91E1BBA5EEA" size="8388608"/>					<videoid>VoeunHdyb4k</videoid>					<plot>Sarge's Heroes 2 starts where Sarge's Heroes left off. It is announced that the capture of Field Marshal Tannenberg will end the war. Since General Plastro has disappeared, it is suggested that he has become a victim of plastrification and been trapped in the real world. The game introduces Bridgette Bleu, a spy for the Blue Nation. She has developed a serum that reverses plastrification. Your job as Sarge and sometimes Vikki is to destroy the serum, eliminate Tan soldiers, and capture Plastro and Tannenburg.</plot>					<genre>Action</genre>					<nplayers>4+</nplayers>					<studio>3DO</studio>					<releasedate>07/15/2000</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1061-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1061-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1061-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1061-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1061-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1061.png</clearlogo1>			</game>			<game name="Asteroids Hyper 64 (USA)">					<description>Asteroids Hyper 64 (USA)</description>					<rom crc="fb982b44" name="Asteroids Hyper 64 (USA).zip" sha1="6E1C4AF8F765DEE69B5308EC5A0B20BC7FB8D862" size="4194304"/>					<videoid>tUgIdB8UWFc</videoid>					<plot>Asteroids Hyper 64 is an updated version of the classic arcade blast 'em up and features full 3D environments, all new weapons and defense systems and a 2 player split-screen mode. The gameplay, however, is exactly the same. Pilot a spacecraft and destroy the on-coming asteroids, each of different sizes. Alien ships and black holes are also out there, along with ship upgrades that update your ships weapons and defense systems.</plot>					<genre>ActionPuzzle</genre>					<nplayers>4+</nplayers>					<studio>Crave</studio>					<releasedate>12/15/1999</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1062-2.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1062-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1062-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1062-1.jpg</snapshot1>					<banner1>http://thegamesdb.n