<?xml version="1.0" ?><!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_launcher (#PCDATA)>		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>			<header>					<emu_name>Nintendo Entertainment System - NES 2nd Source</emu_name>					<emu_parser>NoIntro_parser.xml</emu_parser>					<emu_description>No-Intro_NES</emu_description>					<emu_category>Nintendo</emu_category>					<emu_version>08102015</emu_version>					<emu_date>06/14/2013</emu_date>					<emu_author>no-intro</emu_author>					<emu_homepage>http://www.no-intro.org</emu_homepage>					<emu_baseurl>http://archive.org/download/No-Intro-Collection_2013-06-14/No-Intro-Collection_2013-06-14.zip/Nintendo%20-%20Nintendo%20Entertainment%20System%2F</emu_baseurl>					<emu_launcher>retroplayer</emu_launcher>					<emu_ext_launch_cmd>none</emu_ext_launch_cmd>					<emu_downloadpath>default</emu_downloadpath>					<emu_postdlaction>none</emu_postdlaction>					<emu_comment>No Intro NES List by Zach Morris, removed all beta, and Non-USA games.  Second available source.The Nintendo Entertainment System (also abbreviated as NES or simply called Nintendo) is an 8-bit video game console that was released by Nintendo in North America during 1985, in Europe during 1986 and Australia in 1987. In most of Asia, including Japan (where it was first launched in 1983), China, Vietnam, Singapore, the Middle East and Hong Kong, it was released as the Family Computer, commonly shortened as either the romanized contraction Famicom, or abbreviated to FC. In South Korea, it was known as the Hyundai Comboy, and was distributed by Hynix which then was known as Hyundai Electronics. As the best-selling gaming console of its time, the NES helped revitalize the US video game industry following the video game crash of 1983, and set the standard for subsequent consoles of its generation. With the NES, Nintendo introduced a now-standard business model of licensing third-party developers, authorizing them to produce and distribute software for Nintendo's platform.Developer:  NintendoManufacturer:  NintendoCPU:  Ricoh 2A03Memory:  2KB RAMGraphics:  RP2C02Sound:  Pulse Code ModulationDisplay:  RGBMedia:  CartridgeMax. Controllers:  2</emu_comment>					<emu_thumb>http://thegamesdb.net/banners/platform/boxart/7-1.jpg</emu_thumb>					<emu_banner>http://thegamesdb.net/banners/platform/banners/7-1.png</emu_banner>					<emu_fanart>http://upload.wikimedia.org/wikipedia/commons/8/82/NES-Console-Set.jpg</emu_fanart>					<emu_logo>http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/NES_logo.svg/1280px-NES_logo.svg.png</emu_logo>					<emu_trailer>XSZ58GdFjrs</emu_trailer>					</header>			<game name="10-Yard Fight (USA, Europe)">					<description>10-Yard Fight (USA, Europe)</description>					<rom crc="3d564757" name="10-Yard Fight (USA, Europe).zip" sha1="016818BF6BAAF779F4F5C1658880B81D23EA40CA" size="40960"/>					<videoid>90PSN3lEuGY</videoid>					<plot>The game is viewed in a top-down perspective and is vertical scrolling. The player does not select plays for either offense or defense. On offense, the player simply receives the ball upon the snap and either attempt to run with the quarterback, toss the ball to one of two running backs, or throw the ball to the one long distance receiver - basically the option offense. On defense, the player chooses one of two players to control, and the computer manipulates the others. The ball can also be punted or a field goal can be attempted.</plot>					<genre>Sports</genre>					<nplayers>2</nplayers>					<studio>Taito</studio>					<releasedate>10/18/1985</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/317-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/317-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/317-2.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/317-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/317-2.jpg</snapshot2>					<banner1>http://thegamesdb.net/banners/graphical/317-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/317.png</clearlogo1>					</game>			<game name="1943 - The Battle of Midway (USA)">					<description>1943 - The Battle of Midway (USA)</description>					<rom crc="12c6d5c7" name="1943 - The Battle of Midway (USA).zip" sha1="1E76A86398F069DA43B25351EF419BE664D630C5" size="131072"/>					<videoid>AHnUzNUsKuc</videoid>					<plot>The game is set in the Pacific theater of World War II, off the coast of the Midway Atoll. The goal is to attack the Japanese Air Fleet that bombed the players' American Aircraft Carrier, pursue all Japanese Air and Sea forces, fly through the 16 levels of play, make their way to the Japanese battleship Yamato and destroy her. 11 Levels consist of an Air-to-Sea battle (with a huge battleship or an aircraft carrier as an End-Level Boss), while 5 levels consist of an all-aerial battle against a squadron of Japanese Bombers and a Mother Bomber that needs to be destroyed.</plot>					<genre>Shooter</genre>					<nplayers>2</nplayers>					<studio>Capcom</studio>					<releasedate>06/01/1987</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1018-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1018-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1018-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1018-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1018-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1018-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1018.png</clearlogo1>					</game>			<game name="3-D WorldRunner (USA)">					<description>3-D WorldRunner (USA)</description>					<rom crc="e6a477b2" name="3-D WorldRunner (USA).zip" sha1="CE70E57475F4058AC5A05DFED92163D42F0B8B96" size="131072"/>					<videoid>ETXonCYjSuM</videoid>					<plot>3-D WorldRunner features many elements that are typical of a forward-scrolling rail shooter game, where the player focuses on destroying or dodging onscreen enemies against a scrolling background. 3-D WorldRunner incorporates a distinct third-person view, where the camera angle is positioned behind the main character.As WorldRunner, players make their way through eight worlds, battling hostile alien creatures and leaping over bottomless canyons. Each world is divided into different quadrants, and the player must pass through each quadrant before the time counter on the bottom of the game screen reaches zero. In each quadrant, the player can find pillar-like columns that house power-ups, objects that are beneficial or add extra abilities to the game character. At the end of each world's last quadrant is a serpent-like creature which must be defeated to advance. A status bar at the bottom of the screen displays the player's score, the time counter, the world number, the world quadrant, the number of bonus stars (items that increase the player's score count) collected by the player, and the number of lives, or continues, remaining.</plot>					<genre>Shooter</genre>					<nplayers>1</nplayers>					<studio>Acclaim</studio>					<releasedate>09/12/1987</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/315-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/315-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/315-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/315-1.jpg</snapshot1>					</game>			<game name="720 Degrees (USA)">					<description>720 Degrees (USA)</description>					<rom crc="49f745e0" name="720 Degrees (USA).zip" sha1="57690BE45879AA00DD825B89FC525E31FDC041FF" size="131072"/>					<plot>The game begins with the player controlling a skateboarder skating around a middle-class neighborhood using common objects as ramps for jumps.The player begins with a number of &quot;tickets,&quot; each of which granting admission to one of four skate parks, or &quot;events,&quot; in Skate City, the &quot;hub&quot; between the parks. When a park is entered, one ticket is expended. The player gains additional tickets from earning points. Whenever the player isn't in an event, a bar counts down the time remaining until the arrival of deadly, skateboarder-hungry killer bees. Once the bees arrive the player still has a small amount of time with which to get to a park, but the longer the player delays this the faster the bees become, until they are unavoidable. Getting caught by the bees ends the game, though on default settings the player may elect to continue his game by inserting more money. Reaching a park with a ticket gives the player the chance to earn points, medals and money with which to upgrade his equipment, and resets the timer.The player is constantly racing to perform stunts, both in the events and in the park itself, in order to earn the points needed to acquire tickets. Thus, the players score is directly tied to the amount of time he has to play the game. In order to win, the player must complete a total of sixteen events through four hubs, a difficult task.</plot>					<genre>Sports</genre>					<nplayers>2</nplayers>					<studio>Mindscape</studio>					<releasedate>11/01/1989</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/22196-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/22196-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/22196-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/22196-1.jpg</snapshot1>					<videoid>o087gwEhOdM</videoid>					</game>			<game name="8 Eyes (USA)">					<description>8 Eyes (USA)</description>					<rom crc="326ab3b6" name="8 Eyes (USA).zip" sha1="C74D5CD42C2D29B3358A59FD66757EB00B130A75" size="262144"/>					<videoid>S65SjcsLQ64</videoid>					<plot>8 Eyes is set in a post-apocalyptic future. Mankind is recovering from hundreds of years of chaos and nuclear war, and civilization is being rebuilt by the Great King, who harnesses the power of the eight jewels. The jewels, known as the 8 Eyes, were formed at the centers of eight nuclear explosions that came close to destroying the Earth. The 8 Eyes have mysterious power which, in the wrong hands, could bring about the end of the world. The Great King's eight power-hungry dukes steal the jewels for themselves and banish the King to the nuclear wastelands, threatening to once again plunge the Earth into war.The player controls Orin the Falconer and his fighting falcon Cutrus. His mission is to penetrate the Dukes' eight castles and retrieve the 8 Eyes. With the help of Cutrus, you must fight the Dukes' soldiers, nuclear mutants, and the duke of each castle to retrieve the jewels. After the jewels have been recovered, you must return them to the Altar of Peace so that the Great King may return and finish rebuilding the Earth.</plot>					<genre>Adventure</genre>					<nplayers>2</nplayers>					<studio>Taxan</studio>					<releasedate>01/01/1990</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/316-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/316-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/316-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/316-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/316-2.jpg</snapshot2>					</game>			<game name="Abadox - The Deadly Inner War (USA)">					<description>Abadox - The Deadly Inner War (USA)</description>					<rom crc="b134d713" name="Abadox - The Deadly Inner War (USA).zip" sha1="FEB83967ED5418547D5A56DEA30A270684A6DF6C" size="262144"/>					<plot>In the year 5012, the planet known as Abadox is soon eaten by a giant alien organism known as Parasitis. Once the planet has been consumed, the alien takes the form of the entire planet and seeks to devour other planets within the galaxy. The galactic military tries to fight the alien, but to no avail as Parasitis destroys the entire galactic military, except for one hospital ship. It is then discovered that Princess Maria has been devoured as well. The galactic military decides to send out their best fighter, &quot;Second Lieutenant Nazal&quot;, to attempt to enter Parasitis' body and rescue Princess Maria before it's too late.</plot>					<genre>Shooter</genre>					<nplayers>1</nplayers>					<studio>Natsume</studio>					<releasedate>12/15/1989</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1501-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1501-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1501-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1501-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1501-2.jpg</snapshot2>					</game>			<game name="Addams Family, The (USA)">					<description>Addams Family, The (USA)</description>					<rom crc="65518eae" name="Addams Family, The (USA).zip" sha1="D08992699355195E9ED4DCA2110FE9FC338ED652" size="262144"/>					<videoid>qkULjUIFYZI</videoid>					<plot>The Addams Family father and husband, Gomez Addams, as he attempts to save the members of his family who have been kidnapped. They have been stowed away in various locations in the mansion and are protected by a boss of some sort. The manservant Lurch and the severed hand Thing are the only characters not to be kidnapped.</plot>					<genre>Adventure</genre>					<nplayers>1</nplayers>					<studio>Ocean</studio>					<releasedate>01/01/1992</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1048-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1048-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1048-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1048-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1048-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1048-g.jpg</banner1>					</game>			<game name="Addams Family, The - Pugsley's Scavenger Hunt (USA)">					<description>Addams Family, The - Pugsley's Scavenger Hunt (USA)</description>					<rom crc="063e5653" name="Addams Family, The - Pugsley's Scavenger Hunt (USA).zip" sha1="0D565384E36F490A0A3B555BED51F28B7939663A" size="262144"/>					<videoid>u2eiT3BefGg</videoid>					<plot>The plot of Pugsley's Scavenger Hunt centered around Pugsley's attempts to win a scavenger hunt challenge proposed by his sister, Wednesday. His hunt takes him to the bedrooms of each member of the Addams family in order to find one item from each.</plot>					<genre>Adventure</genre>					<nplayers>1</nplayers>					<studio>Ocean Software</studio>					<releasedate>01/01/1992</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1502-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1502-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1502-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1502-1.jpg</snapshot1>					</game>			<game name="Addams Family, The - Uncle Fester's Quest (USA) (Beta)">					<description>Addams Family, The - Uncle Fester's Quest (USA) (Beta)</description>					<rom crc="f471827d" name="Addams Family, The - Uncle Fester's Quest (USA) (Beta).zip" sha1="4E717A133C5B0C7101D1E8D784263A2C9FAB294B" size="262144"/>					<videoid>nkzN9x2cVT0</videoid>					<fanart1>http://i.ytimg.com/vi/--mFpdu8F6Q/maxresdefault.jpg</fanart1>					<boxart2>http://gamesdbase.com/Media/SYSTEM/Nintendo_Arcade_Systems/Title/big/Uncle_Fester-s_Quest-_The_Addams_Family_-_1989_-_SunSoft,_Ltd..jpg</boxart2>					<boxart1>http://vignette4.wikia.nocookie.net/egamia/images/e/e4/FestersQuestNES.jpg</boxart1>					</game>			<game name="Advanced Dungeons &amp; Dragons - DragonStrike (USA)">					<description>Advanced Dungeons &amp; Dragons - DragonStrike (USA)</description>					<rom crc="2c5908a7" name="Advanced Dungeons &amp; Dragons - DragonStrike (USA).zip" sha1="2A12752F779F83782196EB0CD4DC1E426059D305" size="524288"/>					<videoid>yaFCp_kcmfo</videoid>					<plot>The game is set in Krynn, world of the Dragonlance saga, during the War of the Lance. DragonStrike combined elements of computer role-playing games and flight simulators. The player character is a knight who flies on the back of a metallic dragon equipped with a lance and various magic items (among other things a magic orb that acts as a radar in the game).</plot>					<genre>Role-Playing</genre>					<nplayers>1</nplayers>					<studio>Strategic Simulations</studio>					<releasedate>07/01/1992</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1503-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1503-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1503-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1503-1.jpg</snapshot1>					</game>			<game name="Advanced Dungeons &amp; Dragons - Heroes of the Lance (USA)">					<description>Advanced Dungeons &amp; Dragons - Heroes of the Lance (USA)</description>					<rom crc="b17574f3" name="Advanced Dungeons &amp; Dragons - Heroes of the Lance (USA).zip" sha1="50E76171AA106895C745E7A4F8D9852DB72AAD12" size="262144"/>					<videoid>WZIJ_uYjVZY</videoid>					<plot>While Heroes of the Lance is a faithful representation of the books it is based on, it was a departure from the usual RPG style of most Dungeons &amp; Dragons games, and many players lamented its difficult game play interface which consists of using one character at a time in horizontally-scrolling fighting. Each character has different types of attacks and spells making them more suited to fighting different enemies but they merely act as &quot;lives&quot; for the player as in more traditional fighting games, removing one of the main strategies of role-playing games from the game.</plot>					<genre>Role-Playing</genre>					<studio>U.S. Gold</studio>					<releasedate>01/01/1988</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1021-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1021-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1021-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1021-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1021-g.jpg</banner1>					</game>			<game name="Advanced Dungeons &amp; Dragons - Hillsfar (USA)">					<description>Advanced Dungeons &amp; Dragons - Hillsfar (USA)</description>					<rom crc="5de61639" name="Advanced Dungeons &amp; Dragons - Hillsfar (USA).zip" sha1="B2662816D0367143D41A697B7B714F312E9AC125" size="262144"/>					<videoid>QZUMyNOdkFc</videoid>					<plot>Hillsfar is a single-hero role-playing game (in comparison to other Advanced Dungeons &amp; Dragons role-playing games, where the player usually controls a group of characters). A combination of first person perspective (when traveling in the city of Hillsfar) and third person perspective (usually in some action-style mini-quests) viewpoints.As a would-be-hero, four classes are available in a randomly generated mission-based plot: fighter, thief, cleric, or magic-user. Each class to a certain extent, have different assigned quests given by each respective guild.</plot>					<genre>Role-Playing</genre>					<nplayers>1</nplayers>					<studio>FCI</studio>					<releasedate>01/01/1992</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1608-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1608-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1608-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1608-1.jpg</snapshot1>					</game>			<game name="Advanced Dungeons &amp; Dragons - Pool of Radiance (USA)">					<description>Advanced Dungeons &amp; Dragons - Pool of Radiance (USA)</description>					<rom crc="25952141" name="Advanced Dungeons &amp; Dragons - Pool of Radiance (USA).zip" sha1="65164022F5F3354B168972CC3FF85F4F01808169" size="655360"/>					<videoid>BxE2ARzeoCE</videoid>					<plot>Pool of Radiance takes place in the Forgotten Realms fantasy world. The main setting is the city of Phlan, located on the northern shore of the Moonsea, situated between Zhentil Keep and Melvaunt. The party begins in the civilized section of &quot;New Phlan&quot; that is governed by a council. This portion of the city hosts businesses, including shopkeepers who sell holy items for each temple's worshipers, a jewelry shop, and retailers who provide arms and armor. A party can also contract with the clerk of the city council for various commissions; proclamations fastened to the halls within City Hall offer bits of information to aid the party. These coded clues can be deciphered by using the Adventurer's Journal, included with the game.</plot>					<genre>Role-PlayingStrategy</genre>					<nplayers>1</nplayers>					<studio>FCI</studio>					<releasedate>06/28/1991</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1505-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1505-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1505-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1505-1.jpg</snapshot1>					</game>			<game name="Adventure Island 3 (USA)">					<description>Adventure Island 3 (USA)</description>					<rom crc="bfbfd25d" name="Adventure Island 3 (USA).zip" sha1="F77EB86932844A92834EF12C059A3F5B815DAC07" size="262144"/>					<plot>The gameplay and the design haven't much changed since Adventure Island II.  There is a world map, you can choose items before starting a level, the levels themselves are quite short (unlike Adventure Island, where each large level contained several stages).  You perform standard &quot;adventure island&quot; activities: ride various types of dinosaurs, throw boomerangs at snails, birds, snakes and skulls, collect grapes and apples, jump over stones and, of course, ride your old trusty skateboard.</plot>					<genre>ActionAdventure</genre>					<nplayers>1</nplayers>					<studio>Hudson Soft</studio>					<releasedate>07/31/1992</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1509-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1509-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1509-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1509-1.jpg</snapshot1>					<videoid>-oOkaTIJmgk</videoid>					</game>			<game name="Adventure Island II (USA)">					<description>Adventure Island II (USA)</description>					<rom crc="771c8855" name="Adventure Island II (USA).zip" sha1="D30741F41F76B34C08032FC61579DC5963F1443D" size="262144"/>					<plot>Soar into action with Adventure Island II. That Evil Witch Doctor's just snatched your favorite lady. And you've got to battle your way past EIGHT treacherous islands to get her back.Combat prehistoric monsters -- some of the creepiest, fire-spitting critters ever to slither across a video screen! Survive molten volcanoes. Dodge giant scorpions and king cobras. And the action gets even crazier with a new vertical/horizontal scroll, while stage select lets you control play.So sharpen your axe, slip on a leopard skin, and take off for ADVENTURE ISLAND II. It's gonna be a wild ride!!!</plot>					<genre>ActionAdventure</genre>					<nplayers>1</nplayers>					<studio>Hudson Soft</studio>					<releasedate>01/01/1991</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1023-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1023-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1023-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1023-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1023-g.jpg</banner1>					<videoid>zcS3VMFTPnw</videoid>					</game>			<game name="Adventures in the Magic Kingdom (USA)">					<description>Adventures in the Magic Kingdom (USA)</description>					<rom crc="5dbd6099" name="Adventures in the Magic Kingdom (USA).zip" sha1="F2F932F772E449A29854DCC4B4BF2EFBB09CD0AD" size="262144"/>					<videoid>46wALX1ain4</videoid>					<plot>The game places you as a non-choosable main character. Goofy left the golden key for the castle gate inside, and Mickey Mouse asks your help to find six silver keys needed to open the Cinderella Castle gate and allow the Disney parade to begin. The player must complete five different stages, modeled after rides in Disney theme parks, as well as a trivia quest in order to retrieve the keys. Following this, Mickey congratulates the player and the parade begins.</plot>					<genre>Action</genre>					<nplayers>1</nplayers>					<studio>Capcom</studio>					<releasedate>12/10/1992</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1024-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1024-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1024-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1024-1.jpg</snapshot1>					<banner1>http://thegamesdb.net/banners/graphical/1024-g.jpg</banner1>					</game>			<game name="Adventures of Bayou Billy, The (USA)">					<description>Adventures of Bayou Billy, The (USA)</description>					<rom crc="67751094" name="Adventures of Bayou Billy, The (USA).zip" sha1="7356DD9D129EC32F5DBCBA5C9832E0494995398C" size="262144"/>					<videoid>hVB72Nb5UEg</videoid>					<plot>The player takes control of the title character, Billy West, who must fight save to his girlfriend Annabelle Lane from the gang of Godfather Gordon. There are a total of ten stages in all: six side-scrolling beat-em-up stages (or street fighting stages, as the game actually dubs them), two light gun shooting (shoot-'em-up) stages, and two action driving stages.</plot>					<