<!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_launcher (#PCDATA)>		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT emu_command (#PCDATA)>		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>			<emu_name>Sega Saturn</emu_name>			<emu_parser>NoIntro_parser.xml</emu_parser>			<emu_description>Sega Saturn</emu_description>			<emu_category>Sega</emu_category>			<emu_version>093015</emu_version>			<emu_date>09/30/2015</emu_date>			<emu_author>Zach Morris</emu_author>			<emu_homepage>http://www.no-intro.org</emu_homepage>			<emu_baseurl>http://archive.org/download/</emu_baseurl>			<emu_launcher>retroplayer</emu_launcher>			<emu_ext_launch_cmd>none</emu_ext_launch_cmd>			<emu_downloadpath>default</emu_downloadpath>			<emu_postdlaction>convert_chd_bin</emu_postdlaction>			<emu_comment>MESS Sega Saturn List by Zach Morris.The Sega Saturn is a 32-bit fifth-generation home video game console that was developed by Sega and released in 1994 in Japan as the successor to the successful Sega Genesis. Saturn has a dual-CPU architecture and a total of eight processors. Its games are in CD-ROM format, and its game library contains several arcade ports as well as original titles.Developer:  SegaManufacturer:  SegaCPU:  2 Ã— Hitachi SH-2 32-bit RISCMemory:  1 MB SDRAM as work RAM for both SH-2 CPUsGraphics:  Custom VDP 1 32-bit video display processorSound:  Yamaha FH1 DSPDisplay:  320x240Media:  CDMax. Controllers:  2</emu_comment>			<emu_thumb>http://thegamesdb.net/banners/platform/boxart/17-1.jpg</emu_thumb>			<emu_banner>http://thegamesdb.net/banners/platform/banners/17-1.jpg</emu_banner>			<emu_fanart>https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Sega-Saturn-Console-Set-Mk1.jpg/1280px-Sega-Saturn-Console-Set-Mk1.jpg</emu_fanart>			<emu_logo>https://upload.wikimedia.org/wikipedia/de/thumb/a/a9/Sega_Saturn_Logo.svg/1075px-Sega_Saturn_Logo.svg.png</emu_logo>			<emu_trailer>YNEe04UwJ6Q</emu_trailer>		</header>			<game name="2Tax Gold (Jpn)">					<description>2Tax Gold (Jpn)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F2taxgold%2F2tax%20gold%20%28t-4305g%29.chd" size="380858710"/>					<releasedate>01/01/1997</releasedate>					<studio>Human</studio>					<plot>2Tax Gold () is a quiz game for the Sega Saturn.</plot>					<genre>Puzzle</genre>					<releasedate>01/17/1997</releasedate>					<nplayers>1</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/31327-1.jpg</boxart1>			</game>			<game name="3D Baseball: The Majors (USA)">					<description>3D Baseball: The Majors (USA)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3dbball%2F3d%20baseball%20%28j%29%20%28t-18003g%29.chd" size="100550172"/>					<releasedate>01/01/1996</releasedate>					<studio>Crystal Dynamics</studio>					<plot>Crystal Dynamics presents the most realistic baseball video game ever published. Real Motion Control 3D technology serves up incredibly life-like 3D polygonal models that bit, pitch, and hit like real players.</plot>					<genre>Sports</genre>					<releasedate>11/30/1996</releasedate>					<nplayers>1-2s</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/14398-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/14398.png</clearlogo1>			</game>			<game name="3D Baseball: The Majors (USA)">					<description>3D Baseball: The Majors (USA)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3dbball%2Fsat-0842-3d_baseball-usa.chd" size="100548792"/>					<releasedate>01/01/1996</releasedate>					<studio>Crystal Dynamics</studio>					<plot>Crystal Dynamics presents the most realistic baseball video game ever published. Real Motion Control 3D technology serves up incredibly life-like 3D polygonal models that bit, pitch, and hit like real players.</plot>					<genre>Sports</genre>					<releasedate>11/30/1996</releasedate>					<nplayers>1-2s</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/14398-1.jpg</boxart1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/14398.png</clearlogo1>			</game>			<game name="3D Lemmings (Euro)">					<description>3D Lemmings (Euro)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3dlemmin%2F3d%20lemmings%20%28e%29.chd" size="308726707"/>					<releasedate>01/01/1996</releasedate>					<studio>Psygnosis</studio>					<plot>There is no actual narrative to the game. The only introduction is a movie. It shows a completely flat (2D) lemming popping out of a computer's floppy drive, and finding a &quot;3D&quot; button to press, which makes him 3-dimensional. After that, the PC blows up and the (now 3D) lemmings inside it escape. Other movies play after completing each set of 20 levels, but are not connected by a storyline.</plot>					<genre>Puzzle</genre>					<releasedate>01/01/1996</releasedate>					<nplayers>1</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/5509-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/77681-lemmings-3d-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/5509-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/77680-lemmings-3d-sega-saturn-back-cover.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/77922-lemmings-3d-sega-saturn-media.jpg</boxart5>					<snapshot1>http://www.mobygames.com/images/shots/l/204364-lemmings-3d-sega-saturn-screenshot-clockwork-games-logo.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/204365-lemmings-3d-sega-saturn-screenshot-psygnosis-logo.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/204369-lemmings-3d-sega-saturn-screenshot-an-intro-shot.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/204366-lemmings-3d-sega-saturn-screenshot-the-title-screen-this-one.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/204367-lemmings-3d-sega-saturn-screenshot-you-need-to-complete-all.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/204368-lemmings-3d-sega-saturn-screenshot-when-running-on-a-us-saturn.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/204371-lemmings-3d-sega-saturn-screenshot-in-practice-mode-the-game.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/204372-lemmings-3d-sega-saturn-screenshot-it-also-includes-some-friendly.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/204373-lemmings-3d-sega-saturn-screenshot-introducing-the-para-lemmings.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/204375-lemmings-3d-sega-saturn-screenshot-level-complete.jpg</snapshot10>					<banner1>http://thegamesdb.net/banners/graphical/5509-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/5509.png</clearlogo1>			</game>			<game name="3D Lemmings (Euro)">					<description>3D Lemmings (Euro)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3dlemmin%2F3d%20lemmings%20%28t-15013g%29.chd" size="308754592"/>					<releasedate>01/01/1996</releasedate>					<studio>Psygnosis</studio>					<plot>There is no actual narrative to the game. The only introduction is a movie. It shows a completely flat (2D) lemming popping out of a computer's floppy drive, and finding a &quot;3D&quot; button to press, which makes him 3-dimensional. After that, the PC blows up and the (now 3D) lemmings inside it escape. Other movies play after completing each set of 20 levels, but are not connected by a storyline.</plot>					<genre>Puzzle</genre>					<releasedate>01/01/1996</releasedate>					<nplayers>1</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/5509-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/77681-lemmings-3d-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/5509-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/77680-lemmings-3d-sega-saturn-back-cover.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/77922-lemmings-3d-sega-saturn-media.jpg</boxart5>					<snapshot1>http://www.mobygames.com/images/shots/l/204364-lemmings-3d-sega-saturn-screenshot-clockwork-games-logo.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/204365-lemmings-3d-sega-saturn-screenshot-psygnosis-logo.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/204369-lemmings-3d-sega-saturn-screenshot-an-intro-shot.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/204366-lemmings-3d-sega-saturn-screenshot-the-title-screen-this-one.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/204367-lemmings-3d-sega-saturn-screenshot-you-need-to-complete-all.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/204368-lemmings-3d-sega-saturn-screenshot-when-running-on-a-us-saturn.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/204371-lemmings-3d-sega-saturn-screenshot-in-practice-mode-the-game.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/204372-lemmings-3d-sega-saturn-screenshot-it-also-includes-some-friendly.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/204373-lemmings-3d-sega-saturn-screenshot-introducing-the-para-lemmings.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/204375-lemmings-3d-sega-saturn-screenshot-level-complete.jpg</snapshot10>					<banner1>http://thegamesdb.net/banners/graphical/5509-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/5509.png</clearlogo1>			</game>			<game name="Three Dirty Dwarves (USA)">					<description>Three Dirty Dwarves (USA)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3dwarves%2Fsat-0820-three_dirty_dwarves-usa.chd" size="285490305"/>					<releasedate>01/01/1997</releasedate>					<studio>Sega</studio>					<plot>Four genetically altered geeks have opened the trans-dimensional gates to reality and summoned a rag-tag posse of filthy orc dwarves to rescue them from their maniacal captor. Run amuch with up to 3 players, through over 20 hard-hitting whacko worlds of car-tooney ghettos and freaked-out bosses!</plot>					<genre>Action</genre>					<releasedate>05/29/1997</releasedate>					<nplayers>2</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/11360-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/70090-three-dirty-dwarves-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/11360-1.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/70092-three-dirty-dwarves-sega-saturn-back-cover.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/70091-three-dirty-dwarves-sega-saturn-media.jpg</boxart5>					<snapshot1>http://thegamesdb.net/banners/screenshots/11360-1.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/548409-three-dirty-dwarves-sega-saturn-screenshot-title-screen.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/548410-three-dirty-dwarves-sega-saturn-screenshot-fmv-intro.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/548411-three-dirty-dwarves-sega-saturn-screenshot-first-level.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/548412-three-dirty-dwarves-sega-saturn-screenshot-boss-fight.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/548413-three-dirty-dwarves-sega-saturn-screenshot-bouncing-bed-stage.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/548414-three-dirty-dwarves-sega-saturn-screenshot-weird-enemies-in.jpg</snapshot7>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/11360.png</clearlogo1>			</game>			<game name="3x3 Eyes - Kyuusei Koushu S (Jpn) Disc 1">					<description>3x3 Eyes - Kyuusei Koushu S (Jpn) Disc 1</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3x3eyes%2F3x3%20eyes%20disc%201%20%28j%29%20%28t-21301g%29.chd" size="297019322"/>					<releasedate>01/01/1996</releasedate>					<studio>Nihon Create</studio>					<plot>3x3 Eyes: Kyuusei Koushu S (), is an adventure game based on the 3x3 Eyes manga.</plot>					<genre>Adventure</genre>					<releasedate>04/19/1996</releasedate>					<nplayers>1</nplayers>					<videoid>c1CVyC9VKcY</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/31328-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/70090-three-dirty-dwarves-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/70092-three-dirty-dwarves-sega-saturn-back-cover.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/70091-three-dirty-dwarves-sega-saturn-media.jpg</boxart4>					<snapshot1>http://www.mobygames.com/images/shots/l/548409-three-dirty-dwarves-sega-saturn-screenshot-title-screen.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/548410-three-dirty-dwarves-sega-saturn-screenshot-fmv-intro.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/548411-three-dirty-dwarves-sega-saturn-screenshot-first-level.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/548412-three-dirty-dwarves-sega-saturn-screenshot-boss-fight.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/548413-three-dirty-dwarves-sega-saturn-screenshot-bouncing-bed-stage.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/548414-three-dirty-dwarves-sega-saturn-screenshot-weird-enemies-in.jpg</snapshot6>			</game>			<game name="3x3 Eyes - Kyuusei Koushu S (Jpn) Disc 2">					<description>3x3 Eyes - Kyuusei Koushu S (Jpn) Disc 2</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3x3eyes%2F3x3%20eyes%20disc%202%20%28j%29%20%28t-21301g%29.chd" size="209158337"/>					<releasedate>01/01/1996</releasedate>					<studio>Nihon Create</studio>					<plot>3x3 Eyes: Kyuusei Koushu S (), is an adventure game based on the 3x3 Eyes manga.</plot>					<genre>Adventure</genre>					<releasedate>04/19/1996</releasedate>					<nplayers>1</nplayers>					<videoid>c1CVyC9VKcY</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/31328-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/70090-three-dirty-dwarves-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/70092-three-dirty-dwarves-sega-saturn-back-cover.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/70091-three-dirty-dwarves-sega-saturn-media.jpg</boxart4>					<snapshot1>http://www.mobygames.com/images/shots/l/548409-three-dirty-dwarves-sega-saturn-screenshot-title-screen.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/548410-three-dirty-dwarves-sega-saturn-screenshot-fmv-intro.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/548411-three-dirty-dwarves-sega-saturn-screenshot-first-level.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/548412-three-dirty-dwarves-sega-saturn-screenshot-boss-fight.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/548413-three-dirty-dwarves-sega-saturn-screenshot-bouncing-bed-stage.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/548414-three-dirty-dwarves-sega-saturn-screenshot-weird-enemies-in.jpg</snapshot6>			</game>			<game name="3x3 Eyes - Kyuusei Koushu S (Jpn) Disc 3">					<description>3x3 Eyes - Kyuusei Koushu S (Jpn) Disc 3</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F3x3eyes%2F3x3%20eyes%20disc%203%20%28j%29%20%28t-21301g%29.chd" size="444857305"/>					<releasedate>01/01/1996</releasedate>					<studio>Nihon Create</studio>					<plot>3x3 Eyes: Kyuusei Koushu S (), is an adventure game based on the 3x3 Eyes manga.</plot>					<genre>Adventure</genre>					<releasedate>04/19/1996</releasedate>					<nplayers>1</nplayers>					<videoid>c1CVyC9VKcY</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/31328-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/70090-three-dirty-dwarves-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/70092-three-dirty-dwarves-sega-saturn-back-cover.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/70091-three-dirty-dwarves-sega-saturn-media.jpg</boxart4>					<snapshot1>http://www.mobygames.com/images/shots/l/548409-three-dirty-dwarves-sega-saturn-screenshot-title-screen.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/548410-three-dirty-dwarves-sega-saturn-screenshot-fmv-intro.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/548411-three-dirty-dwarves-sega-saturn-screenshot-first-level.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/548412-three-dirty-dwarves-sega-saturn-screenshot-boss-fight.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/548413-three-dirty-dwarves-sega-saturn-screenshot-bouncing-bed-stage.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/548414-three-dirty-dwarves-sega-saturn-screenshot-weird-enemies-in.jpg</snapshot6>			</game>			<game name="6 Inch My Darling (Jpn)">					<description>6 Inch My Darling (Jpn)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2F6inchmyd%2F6%20inch%20my%20darling%20%28japan%29.chd" size="236981757"/>					<releasedate>01/01/1998</releasedate>					<studio>KID</studio>					<plot>6inch My Darling is a visual novel romance adventure originally released by KID for Sega Saturn with free for all rating, thus not including adult content. Half a year later, the game was released on PC platform by Airyu with added adult content and altered setting and story elements.The story follows a high-school student, named by the player, who lives with his parents and a younger sister. During his time off of school he is helping his mom by part-time working at the liquor store. One day, upon returning from school, he stumbled on a buried box while taking a path through the woods. Inside was a strangely shaped figuring with a message on the inside of the box lid. Not sure what it all was about, he left it on the desk and went to sleep. The next day, he heard a voice in his room, and while trying to determine the source of the voice he stumbled upon a small girl by the name of Etosera. And by small, it means 6 inches in size. But she wasn't the only one that appeared due to the mysterious box, two more girls, Minty and Pim, just as well, also became his secret roommates. Thus his next couple of weeks filled with surprises and getting to know each other commence, all the way while they are trying to build trust and assess the relationship with humans, namely, the player.</plot>					<genre>Adventure</genre>					<releasedate>1998</releasedate>					<nplayers>1</nplayers>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/31329-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/299404-6inch-my-darling-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/299405-6inch-my-darling-sega-saturn-back-cover.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/299406-6inch-my-darling-sega-saturn-media.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/299407-6inch-my-darling-sega-saturn-other.jpg</boxart5>					<snapshot1>http://www.mobygames.com/images/shots/l/759362-6inch-my-darling-sega-saturn-screenshot-prologue.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/759363-6inch-my-darling-sega-saturn-screenshot-heroine-introduction.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/759364-6inch-my-darling-sega-saturn-screenshot-heroine-introduction.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/759365-6inch-my-darling-sega-saturn-screenshot-heroine-introduction.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/759366-6inch-my-darling-sega-saturn-screenshot-opening-movie.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/759367-6inch-my-darling-sega-saturn-screenshot-main-menu.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/759368-6inch-my-darling-sega-saturn-screenshot-options.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/759369-6inch-my-darling-sega-saturn-screenshot-bgm-player.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/759370-6inch-my-darling-sega-saturn-screenshot-enter-your-name.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/759371-6inch-my-darling-sega-saturn-screenshot-the-class-is-in-progress.jpg</snapshot10>			</game>			<game name="Sega Ages - Afterburner II (Jpn)">					<description>Sega Ages - Afterburner II (Jpn)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2Faburner2%2Fafterburner%20ii%20%28gs-9109%29.chd" size="381274993"/>					<releasedate>01/01/1996</releasedate>					<studio>Sega</studio>					<plot>After Burner II is an arcade-style flight game released by Sega in 1987. It is the second game in the After Burner series. In the game, you fly a F-14 Tomcat jet fighter, gunning down enemies while avoiding incoming fire. Like Out Run, another Sega arcade game, After Burner II came in several versions, the most famous being a large, servo actuated, sit-down cabinet which resembled a cockpit and moved according to the motion of the plane onscreen. The cockpit would bank in the same direction the on-screen aircraft was banking. There was also a more basic upright cabinet version.</plot>					<genre>ActionShooter</genre>					<releasedate>09/27/1996</releasedate>					<nplayers>1</nplayers>					<fanart1>http://thegamesdb.net/banners/fanart/original/9612-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/9612-1.jpg</boxart1>					<boxart2>http://www.mobygames.com/images/covers/l/299404-6inch-my-darling-sega-saturn-front-cover.jpg</boxart2>					<boxart3>http://www.mobygames.com/images/covers/l/299405-6inch-my-darling-sega-saturn-back-cover.jpg</boxart3>					<boxart4>http://www.mobygames.com/images/covers/l/299406-6inch-my-darling-sega-saturn-media.jpg</boxart4>					<boxart5>http://www.mobygames.com/images/covers/l/299407-6inch-my-darling-sega-saturn-other.jpg</boxart5>					<snapshot1>http://thegamesdb.net/banners/screenshots/9612-1.jpg</snapshot1>					<snapshot2>http://www.mobygames.com/images/shots/l/759362-6inch-my-darling-sega-saturn-screenshot-prologue.jpg</snapshot2>					<snapshot3>http://www.mobygames.com/images/shots/l/759363-6inch-my-darling-sega-saturn-screenshot-heroine-introduction.jpg</snapshot3>					<snapshot4>http://www.mobygames.com/images/shots/l/759364-6inch-my-darling-sega-saturn-screenshot-heroine-introduction.jpg</snapshot4>					<snapshot5>http://www.mobygames.com/images/shots/l/759365-6inch-my-darling-sega-saturn-screenshot-heroine-introduction.jpg</snapshot5>					<snapshot6>http://www.mobygames.com/images/shots/l/759366-6inch-my-darling-sega-saturn-screenshot-opening-movie.jpg</snapshot6>					<snapshot7>http://www.mobygames.com/images/shots/l/759367-6inch-my-darling-sega-saturn-screenshot-main-menu.jpg</snapshot7>					<snapshot8>http://www.mobygames.com/images/shots/l/759368-6inch-my-darling-sega-saturn-screenshot-options.jpg</snapshot8>					<snapshot9>http://www.mobygames.com/images/shots/l/759369-6inch-my-darling-sega-saturn-screenshot-bgm-player.jpg</snapshot9>					<snapshot10>http://www.mobygames.com/images/shots/l/759370-6inch-my-darling-sega-saturn-screenshot-enter-your-name.jpg</snapshot10>			</game>			<game name="Arcana Strikes (Jpn)">					<description>Arcana Strikes (Jpn)</description>					<system>MESS_0.149_CHD_saturn_1</system>					<rom name="MESS_0.149_CHD_saturn_1/MESS_0.149_CHD_saturn_1.zip/MESS_0.149_CHD_saturn_1%2Facstrike%2Farcana%20strikes%20%28jpn%29%20%28dw0519%29.chd" size="324997722"/>					<releasedate>01/01/1997</releasedate>					<studio>Takara</studio>					<plot>6inch My Darling is a visual novel romance adventure originally released by KID for Sega Saturn with free for all rating, thus not including adult content. Half a year later, the game was released on PC platform by Airyu with added adult content and altered setting and story elements.The story follows a high-school student, named by the player, who lives with his parents and a younger sister. During his time off of school he is helping his mom by part-time working at the liquor store. One day, upon returning from school, he stumbled on a buried box while taking a path through the woods. Inside was a strangely shaped figuring with a message on the inside of the box lid. Not sure what it all was about, he left it on the desk and went to sleep. The next day, he heard a voice in his room, and while trying to determine the source of the voice he stumbled upon a small girl by the name of Etosera. And by small, it means 6 inches in size. But she wasn't the only one that appeared due to the mysterious box, two more girls, Minty and Pim, just as well, also became his secret roommates. Thus his next couple of weeks filled with surprises and getting to know each other c