<!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>		<header>			<emu_name>Super Nintendo Entertainment System - SNES</emu_name>			<emu_parser>NoIntro_parser.xml</emu_parser>			<emu_description>No-Intro_SNES</emu_description>			<emu_category>Nintendo</emu_category>			<emu_version>20150417-171920</emu_version>			<emu_date>04/17/2015</emu_date>			<emu_author>no-intro</emu_author>			<emu_homepage>http://www.no-intro.org</emu_homepage>			<emu_baseurl>http://archive.org/download/No-Intro-Collection_2015-03-03/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.zip/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System%2F</emu_baseurl>			<emu_downloadpath>default</emu_downloadpath>			<emu_postdlaction>None</emu_postdlaction>			<emu_comment>No Intro SNES List by Zach Morris, removed all beta, and Non-USA games.The Super Nintendo Entertainment System (also known as the Super NES, SNES or Super Nintendo) is a 16-bit video game console that was released by Nintendo in North America, Europe, Australasia (Oceania), and South America between 1990 and 1993. In Japan and Southeast Asia, the system is called the Super Famicom (officially adopting the abbreviated name of its predecessor, the Family Computer), or SFC for short. In South Korea, it is known as the Super Comboy and was distributed by Hyundai Electronics. Although each version is essentially the same, several forms of regional lockout prevent the different versions from being compatible with one another. The Super Nintendo Entertainment System was Nintendo's second home console, following the Nintendo Entertainment System (NES). The console introduced advanced graphics and sound capabilities compared with other consoles at the time. Additionally, development of a variety of enhancement chips (which were integrated on game circuit boards) helped to keep it competitive in the marketplace. The SNES was a global success, becoming the best-selling console of the 16-bit era despite its relatively late start and the fierce competition it faced in North America and Europe from Sega's Genesis console. The SNES remained popular well into the 32-bit era, and although Nintendo no longer offers factory repairs/replacement or accessories for the console, it continues to be popular among fans, collectors, retro gamers, and emulation enthusiasts, some of whom are still making homebrew ROM images.Developer:  NintendoManufacturer:  NintendoCPU:  16-bit 65c816 Ricoh 5A22 3.58 MHzMemory:  128kbGraphics:  N/ASound:  8-bit Sony SPC700Display:  512 Ã— 239Media:  CartridgeMax. Controllers:  2</emu_comment>			<emu_thumb>http://thegamesdb.net/banners/platform/boxart/6-1.jpg</emu_thumb>			<emu_banner>http://thegamesdb.net/banners/platform/banners/6-2.jpg</emu_banner>			<emu_fanart>http://upload.wikimedia.org/wikipedia/commons/3/31/SNES-Mod1-Console-Set.jpg</emu_fanart>			<emu_logo>http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/SNES_logo.svg/1280px-SNES_logo.svg.png</emu_logo>			<emu_trailer>AqhPESyVss8</emu_trailer>		</header>			<game name="2020 Super Baseball (USA)">					<description>2020 Super Baseball (USA)</description>					<rom crc="0d77933e" name="2020 Super Baseball (USA).zip" sha1="F285D6B3717A571002A5E9E0B732F08F100D2514" size="1572864" status="verified"/>					<videoid>LZOu7l3kSy8</videoid>					<plot>Different from real baseball and other baseball video games, this game consists of both male and female characters, as well as robots. All three types of players have the same basic abilities and vary only on their personal strengths. In many cases, human players are better than their robot counterparts. One major difference between the human and robot characters is that the robot characters can blow up (or lose all their power) if they are worked too hard during a game. That can happen if you constantly make them dive for a ball, run extra bases, or even if they get hit by a pitch. Under no stress whatsoever, some robots, especially pitchers, will naturally run out of power as the game progresses. When this happens, they will lose all their abilities and be useless, both offensively and defensively. When that occurs, you can either power them up or replace them with another person on the roster. Human players do not blow up, but human pitchers can tire out. When they are tired, they will pant heavily and throw the ball very slowly. This can be remedied by either an upgrade or, as in real baseball, switching to a relief pitcher.</plot>					<genre>Sports</genre>					<studio>SNK</studio>					<releasedate>03/12/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/304-1.png</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/304-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/304-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/304-3.jpg</snapshot3>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/304.png</clearlogo1>			</game>			<game name="3 Ninjas Kick Back (USA)">					<description>3 Ninjas Kick Back (USA)</description>					<rom crc="f2ee11f9" name="3 Ninjas Kick Back (USA).zip" sha1="B619576A51A3968E243028A830A455D40CF92E78" size="2097152" status="verified"/>					<videoid>18Hcd8P61Wc</videoid>					<plot>You first saw Rocky, Colt and Tum Tum on the silver screen when their martial arts skills and extreme exploits saved the honor of Grandfather Mori and defeated an evil arms dealer.  Now, its up to you!  In this action-packed adventure, you become any one of the 3 Ninjas.  And thats when the fun begins.  Wild animals and even wilder ninjas attack!  A trio of spaced-out heavy metal rockers join forces with the evil Koga in an all-out effort to do you dirty.  But if you rescue Grandfather Mori and his ceremonial dagger, youll have the last laugh and unlock a secret room filled with more gold than Fort Knox!</plot>					<genre>Action</genre>					<nplayers>2</nplayers>					<studio>Sony Imagesoft</studio>					<releasedate>06/01/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/281-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/281-2.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/281-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/281-2.jpg</snapshot2>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/281.png</clearlogo1>			</game>			<game name="7th Saga, The (USA)">					<description>7th Saga, The (USA)</description>					<rom crc="b3abdde6" name="7th Saga, The (USA).zip" sha1="8D2B8AEA636A2239805C99744BF48C0B4DF8D96E" size="1572864" status="verified"/>					<plot>The game takes place on a world called Ticondera. 5000 years ago, a divine being named Saro defeated an evil entity named Gorsia with the power of seven runes. In the years since then, the runes have been scattered across the globe. Lemele, the son of Saro, was born 100 years ago, and became a hero when he defeated the demon Gariso. Now 100 years old, Lemele has become the benevolent and powerful ruler of the world.</plot>					<genre>Role-Playing</genre>					<nplayers>1</nplayers>					<studio>Enix</studio>					<releasedate>08/03/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/282-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/282-2.jpg</boxart1>					<banner1>http://thegamesdb.net/banners/graphical/282-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/282.png</clearlogo1>					<videoid>icX0iqgShoc</videoid>			</game>			<game name="A.S.P. - Air Strike Patrol (USA)">					<description>A.S.P. - Air Strike Patrol (USA)</description>					<rom crc="05c0da54" name="A.S.P. - Air Strike Patrol (USA).zip" sha1="57122EF7A84FBE0355ECC7E0648E39F56854A5F6" size="1048576" status="verified"/>					<videoid>8ivLHu0j_aU</videoid>					<plot>Playing as a jet pilot of the &quot;Coalition&quot; force, players take control of either an F-15 Eagle, or an A-10 Tankbuster jet. The mission is to neutralise the offensive forces of the Zarak army, who have recently invaded a smaller neighbouring country. The Zarak army has many ground units, including tanks, stinger-missile launchers, SCUD missiles and armored vehicles.To accomplish the ultimate goal of defeating the Zarak army, players venture out on numerous missions (called &quot;sorties&quot;) that have varied and specific objectives. Typically, various installations such as radar sites, air bases or ground units are the target. Other missions include disabling an oil-pipeline and destroying SCUD launchers before they fire. Pre-mission screens ask the player to select from the two planes. Then,  the player can specify the armament to carry into the sortie. Air-to-ground and air-to-air missiles are available for each of the planes. Here, a strategic choice between countering either air units or ground units has to be made, as each area (of which there are eight) is patrolled by opposing enemy F-15 jets.</plot>					<genre>Shooter</genre>					<nplayers>1</nplayers>					<studio>SETA</studio>					<releasedate>01/01/1995</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/305-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/305-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/305-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/305-2.jpg</snapshot2>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/305.png</clearlogo1>			</game>			<game name="Aaahh!!! Real Monsters (USA)">					<description>Aaahh!!! Real Monsters (USA)</description>					<rom crc="27ff5ba1" name="Aaahh!!! Real Monsters (USA).zip" sha1="7A4452F38C76A1FAA50AEC790E7E38B069B2471E" size="2097152" status="verified"/>					<videoid>r7oH7-t0EHI</videoid>					<plot>In this game, based on popular Nickelodeon comics, you control three monsters: Ickis, Oblina, and Krumm. The Gromble, a headmaster in monster school, needs you to perform the final test - monster Midterm Exam - in order to prove yourselves to be real monsters. You should collect trash, throw it on people, and scare them!</plot>					<genre>ActionAdventure</genre>					<nplayers>2</nplayers>					<studio>Viacom New Media</studio>					<releasedate>08/15/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/306-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/306-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/306-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/306-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/306-1.jpg</snapshot1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/306.png</clearlogo1>			</game>			<game name="ABC Monday Night Football (USA)">					<description>ABC Monday Night Football (USA)</description>					<rom crc="e0dc8ad7" name="ABC Monday Night Football (USA).zip" sha1="8C6B2B1CD45CF486B64B0F544A34D2D1286C782F" size="1048576" status="verified"/>					<videoid>8sPLJvUYK1g</videoid>					<plot>ABC Sports and Data East team up to take you to the gridiron! Strap on your helmet, put that black stuff under your eyes and prepare yourself for football, Frank Gifford style! Features AFB voice synthesis technology.</plot>					<genre>Sports</genre>					<nplayers>2</nplayers>					<studio>Data East</studio>					<releasedate>12/07/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/1332-1.jpg</boxart2>					<snapshot1>http://thegamesdb.net/banners/screenshots/1332-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1332-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/1332-3.jpg</snapshot3>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1332.png</clearlogo1>			</game>			<game name="ACME Animation Factory (USA)">					<description>ACME Animation Factory (USA)</description>					<rom crc="0944a5c3" name="ACME Animation Factory (USA).zip" sha1="0C739DE2095A9BD310BC19D28E7566FAF894C543" size="1048576" status="verified"/>					<videoid>uyk_RNCgOPQ</videoid>					<plot>In ACME Animation Factory, the player is given a series of tools to create his or her own cartoons, using the most famous characters of Looney Tunes, including graphics, animation and music. When the cartoon has been created, it can be saved and later replayed.</plot>					<genre>Sandbox</genre>					<nplayers>1</nplayers>					<studio>Sunsoft</studio>					<releasedate>11/01/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1528-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1528-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1528-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1528-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/1528-3.jpg</snapshot3>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1528.png</clearlogo1>			</game>			<game name="ActRaiser (USA)">					<description>ActRaiser (USA)</description>					<rom crc="eac3358d" name="ActRaiser (USA).zip" sha1="E8365852CC20178D42C93CD188A7AE9AF45369D7" size="1048576" status="verified"/>					<videoid>8TmgNMgcLk0</videoid>					<plot>During game play the player fills the role of the 'Master', a powerful being awakened from a long sleep to find the civilizations of his former world in shambles. Through a combination of side-scrolling action stages and overhead-view &quot;god&quot; simulation mode the Master slowly rebuilds his world and regains his followers and powers. He is not referred to as a deity of any kind, and it is stated in the manual that he is mortal, and this is the reason he hid away from the demons he was fighting when he had just enough power to seal himself away and wait them out.</plot>					<genre>ActionConstruction and Management Simulation</genre>					<nplayers>1</nplayers>					<studio>Enix</studio>					<releasedate>11/01/1991</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1046-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1046-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1046-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1046-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1046-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1046-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/1046-3.jpg</snapshot3>					<banner1>http://thegamesdb.net/banners/graphical/1046-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1046.png</clearlogo1>			</game>			<game name="ActRaiser 2 (USA)">					<description>ActRaiser 2 (USA)</description>					<rom crc="4901f718" name="ActRaiser 2 (USA).zip" sha1="17C086F3418F7F51E5472270D756EC5112914B83" size="1572864" status="verified"/>					<videoid>hY9kKFa4eiU</videoid>					<plot>The game begins with the universe overrun with evil, with the Master battling with Tanzra. Tanzra, once the Master's servant, led a rebellion against him, but lost and was banished from Heaven.Ripped and torn, the slain body of Tanzra fell to the underworld. Feeding on the intense hatred each held for the Master, Tanzra's seven deadly sins and their minions combined their power to raise the spirit of their mighty leader. Tanzra, now vowing revenge for his defeat by The Master, unleashed these demons upon the world. The player in this game assumes the role of the Master, aided by an angel associate, known as Crystalis.</plot>					<genre>Action</genre>					<nplayers>1</nplayers>					<studio>Enix</studio>					<releasedate>10/29/1993</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1047-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1047-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1047-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1047-2.jpg</snapshot2>					<banner1>http://thegamesdb.net/banners/graphical/1047-g.jpg</banner1>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1047.png</clearlogo1>			</game>			<game name="Addams Family Values (USA) (En,Fr,De)">					<description>Addams Family Values (USA) (En,Fr,De)</description>					<rom crc="98b07db8" name="Addams Family Values (USA) (En,Fr,De).zip" sha1="24848E53E32CC16A30ACCE48D40CE09C37B669C4" size="2097152" status="verified"/>					<videoid>OuFvurCnrHQ</videoid>					<plot>The evil Debbie Jelinksi is harming the Addams family once again... She has kidnapped Baby Pubert, and Uncle Fester is the one who must find him and to bring him back to his loving family. The game is based on the live-action movie of the same name.</plot>					<genre>ActionRole-Playing</genre>					<nplayers>1</nplayers>					<studio>Ocean Software</studio>					<releasedate>01/01/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1531-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1531-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1531-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1531-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1531-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1531-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/1531-3.jpg</snapshot3>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1531.png</clearlogo1>			</game>			<game name="Addams Family, The (USA)">					<description>Addams Family, The (USA)</description>					<rom crc="2e8034ab" name="Addams Family, The (USA).zip" sha1="3F6863985A8C6CFAD71867C2349AA0AC79CB1274" size="1048576" status="verified"/>					<videoid>OuFvurCnrHQ</videoid>					<plot>The evil Debbie Jelinksi is harming the Addams family once again... She has kidnapped Baby Pubert, and Uncle Fester is the one who must find him and to bring him back to his loving family. The game is based on the live-action movie of the same name.</plot>					<genre>ActionRole-Playing</genre>					<nplayers>1</nplayers>					<studio>Ocean Software</studio>					<releasedate>01/01/1995</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1531-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1531-2.jpg</fanart2>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1531-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1531-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/1531-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/1531-2.jpg</snapshot2>					<snapshot3>http://thegamesdb.net/banners/screenshots/1531-3.jpg</snapshot3>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/1531.png</clearlogo1>			</game>			<game name="Addams Family, The - Pugsley's Scavenger Hunt (USA)">					<description>Addams Family, The - Pugsley's Scavenger Hunt (USA)</description>					<rom crc="153a00a7" name="Addams Family, The - Pugsley's Scavenger Hunt (USA).zip" sha1="3419E8A5FEF813BC0234169F9E8055444DC2049B" size="1048576" status="verified"/>					<plot>As if things weren't ooky enough!  Wednesday has devised a simply torturous game which will drive her darling wretched brother, Pugsley, to happiness.  How absolutely delicious!  She has hidden six wonderfully strange items somewhere about the Addams Family Mansion.  Now, you must guide poor Pugsley on his quest to uncover them.Traps, traps, traps you say!  Well, yes.  What else would add so much lovely horror to this unnaturally delightful fun?  Little Wednesday has made sure this adventure will be a doom-filled doozie.  There are hidden switches all about, which produce the loveliest blood-curdling effects when Pugsley runs into them.  And lets not forget all the money that Pugsley will be able to gather on his way.  Theres even magic money which will have an extra lively effect you wont want to miss.  So get ready to get spooky, and get set to get kooky its Pugsleys Scavenger Hunt!  En garde!</plot>					<genre>Platform</genre>					<nplayers>1</nplayers>					<studio>Ocean</studio>					<releasedate>02/01/1993</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/3669-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/3669-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/3669-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/3669-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/3669-2.jpg</snapshot2>			</game>			<game name="Addams Family, The - Pugsley's Scavenger Hunt (USA) (Beta)">					<description>Addams Family, The - Pugsley's Scavenger Hunt (USA) (Beta)</description>					<rom crc="64d68066" name="Addams Family, The - Pugsley's Scavenger Hunt (USA) (Beta).zip" sha1="1FF69C922300D7562E357FBA6FD6EFEB1B8AC0A4" size="1048576"/>					<plot>As if things weren't ooky enough!  Wednesday has devised a simply torturous game which will drive her darling wretched brother, Pugsley, to happiness.  How absolutely delicious!  She has hidden six wonderfully strange items somewhere about the Addams Family Mansion.  Now, you must guide poor Pugsley on his quest to uncover them.Traps, traps, traps you say!  Well, yes.  What else would add so much lovely horror to this unnaturally delightful fun?  Little Wednesday has made sure this adventure will be a doom-filled doozie.  There are hidden switches all about, which produce the loveliest blood-curdling effects when Pugsley runs into them.  And lets not forget all the money that Pugsley will be able to gather on his way.  Theres even magic money which will have an extra lively effect you wont want to miss.  So get ready to get spooky, and get set to get kooky its Pugsleys Scavenger Hunt!  En garde!</plot>					<genre>Platform</genre>					<nplayers>1</nplayers>					<studio>Ocean</studio>					<releasedate>02/01/1993</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/3669-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/3669-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/3669-1.jpg</boxart1>					<snapshot1>http://thegamesdb.net/banners/screenshots/3669-1.jpg</snapshot1>					<snapshot2>http://thegamesdb.net/banners/screenshots/3669-2.jpg</snapshot2>			</game>			<game name="Advanced Dungeons &amp; Dragons - Eye of the Beholder (USA)">					<description>Advanced Dungeons &amp; Dragons - Eye of the Beholder (USA)</description>					<rom crc="20143571" name="Advanced Dungeons &amp; Dragons - Eye of the Beholder (USA).zip" sha1="0368EB078744D97CD499344654401DCA1B184E25" size="1048576" status="verified"/>					<plot>Something evil is lurking below the city of Waterdeep. The Lords of Waterdeep summon a group of heroes to investigate, but someone or something has been watching the proceedings. After the heroes enter the sewers, the ceiling collapses behind them. The only way out is the way down, into a dungeon filled with monsters, traps and puzzles.</plot>					<genre>Role-Playing</genre>					<nplayers>1</nplayers>					<studio>Strategic Simulations, Inc.</studio>					<releasedate>01/01/1994</releasedate>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/284-2.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/284-1.jpg</boxart1>					<banner1>http://thegamesdb.net/banners/graphical/284-g.jpg</banner1>			</game>			<game name="Adventures of Batman &amp; Robin, The (USA)">					<description>Adventures of Batman &amp; Robin, The (USA)</description>					<rom crc="b3ef81f5" name="Adventures of Batman &amp; Robin, The (USA).zip" sha1="5452C639C49906679CAD640AAF60D7F4749F84D3" size="2097152" status="verified"/>					<plot>For the most part, is an action-adventure platformer in which the player only controls Batman, and follows him to the end of each stage, where a villain is set to appear. However, the style and design of the stages themselves are different between each other, which gives notable diversity to the game.</plot>					<genre>Action</genre>					<nplayers>1</nplayers>					<studio>Konami</studio>					<releasedate>12/01/1994</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1049-1.jpg</fanart1>					<fanart2>http://thegamesdb.net/banners/fanart/original/1049-2.jpg</fanart2>					<fanart3>http://thegamesdb.net/banners/fanart/original/1049-3.jpg</fanart3>					<fanart4>http://thegamesdb.net/banners/fanart/original/1049-4.jpg</fanart4>					<fanart5>http://thegamesdb.net/banners/fanart/original/1049-5.jpg</fanart5>					<boxart2>http://thegamesdb.net/banners/boxart/original/back/1049-1.jpg</boxart2>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/1049-1.jpg</boxart1>					<banner1>http://thegamesdb.net/banners/graphical/1049-g.jpg</banner1>					<videoid>D9qaDgx2Xu8</videoid>			</game>			<game name="Adventures of Dr. Franken, The (USA)">					<description>Adventures of Dr. Franken, The (USA)</description>					<rom crc="cfab3bba" name="Adventures of Dr. Franken, The (USA).zip" sha1="4B2334454A3BE9C4C16B86B8EB4B0A352C67B780" size="1048576" status="verified"/>					<videoid>g1pawhw3wGM</videoid>					<plot>The game features Franky, a Frankenstein Monster on a mission to collect the scattered body parts of his girlfriend.</plot>					<genre>Adventure</genre>					<studio>Kemco, DTMC</studio>					<releasedate>12/01/1993</releasedate>					<fanart1>http://thegamesdb.net/banners/fanart/original/1050-1.jpg</fanart1>					<boxart2>http://thegamesdb.net/banners/boxart/original/front/1050-1.jpg</boxart2>					<banner1>http://thegamesdb.net/banners/graphical/1050-g.jpg</banner1>			</game>			<game name="Adventures of Kid Kleets, The (USA) (En,Fr,Es)">					<description>Adventures of Kid Kleets, The (USA) (En,Fr,Es)</description>					<rom crc="1664ae48" name="Adventures of Kid Kleets, The (USA) (En,Fr,Es).zip" sha1="AB1BC78DC622E746262F6CF7B4D248449FBC9509" size="1310720" status="verified"/>					<plot>The World Cup trophy has been stolen, and it's