<?xml version="1.0" ?><!DOCTYPE datafile [<!ELEMENT datafile ANY>	<!ELEMENT header ANY>		<!ELEMENT emu_name (#PCDATA)>		<!ELEMENT emu_parser (#PCDATA)>		<!ELEMENT emu_description (#PCDATA)>		<!ELEMENT emu_category (#PCDATA)>		<!ELEMENT emu_version (#PCDATA)>		<!ELEMENT emu_date (#PCDATA)>		<!ELEMENT emu_author (#PCDATA)>		<!ELEMENT emu_homepage (#PCDATA)>		<!ELEMENT emu_baseurl (#PCDATA)>		<!ELEMENT emu_downloadpath (#PCDATA)>		<!ELEMENT emu_postdlaction (#PCDATA)>		<!ELEMENT emu_comment (#PCDATA)>		<!ELEMENT emu_thumb (#PCDATA)>		<!ELEMENT emu_banner (#PCDATA)>		<!ELEMENT emu_fanart (#PCDATA)>		<!ELEMENT emu_logo (#PCDATA)>		<!ELEMENT emu_trailer (#PCDATA)>	<!ELEMENT game ANY>		<!ATTLIST game name CDATA #REQUIRED>		<!ELEMENT description (#PCDATA)>		<!ELEMENT rom EMPTY>			<!ATTLIST rom name CDATA #REQUIRED>			<!ATTLIST rom size CDATA #REQUIRED>			<!ATTLIST rom crc CDATA #IMPLIED>			<!ATTLIST rom sha1 CDATA #IMPLIED>			<!ATTLIST rom status (baddump|nodump|good|verified) "good">		<!ELEMENT videoid (#PCDATA)>		<!ELEMENT plot (#PCDATA)>		<!ELEMENT genre (#PCDATA)>		<!ELEMENT nplayers (#PCDATA)>		<!ELEMENT studio (#PCDATA)>		<!ELEMENT releasedate (#PCDATA)>		<!ELEMENT fanart1 (#PCDATA)>		<!ELEMENT fanart2 (#PCDATA)>		<!ELEMENT fanart3 (#PCDATA)>		<!ELEMENT fanart4 (#PCDATA)>		<!ELEMENT fanart5 (#PCDATA)>		<!ELEMENT fanart6 (#PCDATA)>		<!ELEMENT fanart7 (#PCDATA)>		<!ELEMENT fanart8 (#PCDATA)>		<!ELEMENT fanart9 (#PCDATA)>		<!ELEMENT fanart10 (#PCDATA)>		<!ELEMENT fanart11 (#PCDATA)>		<!ELEMENT fanart12 (#PCDATA)>		<!ELEMENT fanart13 (#PCDATA)>		<!ELEMENT fanart14 (#PCDATA)>		<!ELEMENT fanart15 (#PCDATA)>		<!ELEMENT fanart16 (#PCDATA)>		<!ELEMENT fanart17 (#PCDATA)>		<!ELEMENT fanart18 (#PCDATA)>		<!ELEMENT fanart19 (#PCDATA)>		<!ELEMENT fanart20 (#PCDATA)>		<!ELEMENT fanart21 (#PCDATA)>		<!ELEMENT fanart22 (#PCDATA)>		<!ELEMENT fanart23 (#PCDATA)>		<!ELEMENT fanart24 (#PCDATA)>		<!ELEMENT fanart25 (#PCDATA)>		<!ELEMENT fanart26 (#PCDATA)>		<!ELEMENT fanart27 (#PCDATA)>		<!ELEMENT fanart28 (#PCDATA)>		<!ELEMENT fanart29 (#PCDATA)>		<!ELEMENT fanart30 (#PCDATA)>		<!ELEMENT boxart1 (#PCDATA)>		<!ELEMENT boxart2 (#PCDATA)>		<!ELEMENT boxart3 (#PCDATA)>		<!ELEMENT boxart4 (#PCDATA)>		<!ELEMENT boxart5 (#PCDATA)>		<!ELEMENT boxart6 (#PCDATA)>		<!ELEMENT boxart7 (#PCDATA)>		<!ELEMENT boxart8 (#PCDATA)>		<!ELEMENT boxart9 (#PCDATA)>		<!ELEMENT boxart10 (#PCDATA)>		<!ELEMENT snapshot1 (#PCDATA)>		<!ELEMENT snapshot2 (#PCDATA)>		<!ELEMENT snapshot3 (#PCDATA)>		<!ELEMENT snapshot4 (#PCDATA)>		<!ELEMENT snapshot5 (#PCDATA)>		<!ELEMENT snapshot6 (#PCDATA)>		<!ELEMENT snapshot7 (#PCDATA)>		<!ELEMENT snapshot8 (#PCDATA)>		<!ELEMENT snapshot9 (#PCDATA)>		<!ELEMENT snapshot10 (#PCDATA)>		<!ELEMENT banner1 (#PCDATA)>		<!ELEMENT banner2 (#PCDATA)>		<!ELEMENT banner3 (#PCDATA)>		<!ELEMENT banner4 (#PCDATA)>		<!ELEMENT banner5 (#PCDATA)>		<!ELEMENT banner6 (#PCDATA)>		<!ELEMENT banner7 (#PCDATA)>		<!ELEMENT banner8 (#PCDATA)>		<!ELEMENT banner9 (#PCDATA)>		<!ELEMENT banner10 (#PCDATA)>		<!ELEMENT clearlogo1 (#PCDATA)>		<!ELEMENT clearlogo2 (#PCDATA)>		<!ELEMENT clearlogo3 (#PCDATA)>		<!ELEMENT clearlogo4 (#PCDATA)>		<!ELEMENT clearlogo5 (#PCDATA)>		<!ELEMENT clearlogo6 (#PCDATA)>		<!ELEMENT clearlogo7 (#PCDATA)>		<!ELEMENT clearlogo8 (#PCDATA)>		<!ELEMENT clearlogo9 (#PCDATA)>		<!ELEMENT clearlogo10 (#PCDATA)>]>	<datafile>			<header>					<emu_name>NEC - PC Engine - TurboGrafx 16</emu_name>					<emu_parser>NoIntro_parser.xml</emu_parser>					<emu_description>No-Intro_TG16</emu_description>					<emu_category>NEC</emu_category>					<emu_version>20150417-171920</emu_version>					<emu_date>04/17/2015</emu_date>					<emu_author>no-intro</emu_author>					<emu_homepage>http://www.no-intro.org</emu_homepage>					<emu_baseurl>http://archive.org/download/No-Intro-Collection_2015-03-03/NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016.zip/NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016%2F</emu_baseurl>					<emu_downloadpath>default</emu_downloadpath>					<emu_postdlaction>None</emu_postdlaction>					<emu_comment>The TurboGrafx-16 Entertainment SuperSystem, originally known in Japan as the PC Engine, is a home video game console joint-developed by Hudson Soft and NEC, released in Japan on October 30, 1987, and in the United States on August 29, 1989. It was the first console released in the 16-bit era, albeit still utilizing an 8-bit CPU. Originally intended to compete with the Nintendo Entertainment System (NES), it ended up competing against the likes of the Sega Mega Drive/Genesis, Super Famicom/Super Nintendo, and even the Neo Geo AES.The TurboGrafx-16 has an 8-bit CPU and a dual 16-bit GPU; and is capable of displaying 482 colors simultaneously, out of 512. The NEC PC Engine once held the record for the world's smallest game console.Developer:  Hudson SoftManufacturer:  NECCPU:  Hudson Soft HuC6280Memory:  64 kBGraphics:  HuC6260Sound:  6 Mini-Wavetable stereo audio channelsDisplay:  256Ã—239Media:  CartridgeMax. Controllers:  2</emu_comment>					<emu_thumb>http://thegamesdb.net/banners/platform/boxart/34-1.jpg</emu_thumb>					<emu_banner>http://thegamesdb.net/banners/platform/banners/34-1.png</emu_banner>					<emu_fanart>https://upload.wikimedia.org/wikipedia/commons/d/d0/TurboGrafx16-Console-Set.jpg</emu_fanart>					<emu_logo>https://upload.wikimedia.org/wikipedia/en/1/19/TurboGrafx16logo.jpg</emu_logo>					<emu_trailer>Xn_xaQ5d5gY</emu_trailer>					</header>			<game name="Aero Blasters (USA)">						<description>Aero Blasters (USA)</description>						<rom crc="b03e0b32" name="Aero Blasters (USA).pce" sha1="23B7DA6A6067563AF5FDF303D83ADEAE818CDCDF" size="524288"/>					<plot>The player controls a small craft through different levels with many enemies. Every level ends with a boss and some section speed up the gameplay, offering fast obstacle courses both horizontally and vertically scrolling. Flying orange pods release many power-ups at once, enhancing the ships with new or more powerful lasers, wing men and shields. The player can also hold the fire key to charge a blast that removes all enemy bullets from the screen and deals damage to all enemies. With an unforgiving difficulty, every hit is fatal, but the game can be continued from any points as long as there are lives and credits left. The game can be played with two players cooperatively.</plot>					<genre>Action</genre>					<releasedate>01/01/1990</releasedate>					<videoid>LAjr4sJrhrs</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/4909-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/2/7/51527_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/4909-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/4/d/f/gfs_4299_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/e/3/d/gfs_57375_1_1.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/4/5/6/gfs_57375_1_2_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/0/1/5/gfs_57375_1_3_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/d/d/c/gfs_57375_1_4_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/e/4/2/gfs_4299_2_1.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/4/9/2/gfs_4299_2_2.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/e/9/2/gfs_57375_2_1_mid.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/2/5/7/gfs_57375_2_2_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/6/1/4/gfs_57375_2_3_mid.jpg</snapshot10>			</game>			<game name="Air Zonk (USA)">						<description>Air Zonk (USA)</description>						<rom crc="933d5bcc" name="Air Zonk (USA).pce" sha1="1EE94B6016FFDF996409955287E8799019A68658" size="524288"/>					<plot>Air Zonk may appear to feature a candy cartoon coating on the outside, but it's still a traditional shoot-'em-up at heart. You still have a selection of your basic weapon power-ups (8 in total here), but spread guns &amp; powerful bursts are now represented by killer decks of cards &amp; giant metal mandibles. Large, imposing endbosses are still the norm, but here your foes range from giant heaps of living garbage to killer football players. And outer space? Who needs to blow up things there when you have other venues (5 in total) such as a gigantic stadium to do it in?</plot>					<genre>Action</genre>					<releasedate>01/01/1992</releasedate>					<videoid>mxgaUfKvKfY</videoid>					<fanart1>http://thegamesdb.net/banners/fanart/original/8185-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8185-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/3/1/51531_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/8185-1.jpg</boxart3>					<snapshot1>http://thegamesdb.net/banners/screenshots/8185-1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/6/8/e/gfs_4300_1_1.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/2/f/8/gfs_57376_1_1.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/8/9/8/gfs_57376_1_2_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/c/d/b/gfs_57376_1_3_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/1/1/2/gfs_57376_1_4_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/5/5/1/gfs_57376_1_5_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/8/6/5/gfs_57376_2_1.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/e/9/9/gfs_57376_2_2_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/a/d/a/gfs_57376_2_3_mid.jpg</snapshot10>			</game>			<game name="Alien Crush (USA)">						<description>Alien Crush (USA)</description>						<rom crc="ea488494" name="Alien Crush (USA).pce" sha1="1BFA4B5139612B0C33E3282C23E56C1DFC08ED52" size="262144"/>					<plot>Imagine a living pinball machine...with aliens and outlandish worlds to throw at you. And turbo-charged, speed-of-light pinball action. You control the flippers and ball speed to defeat the Slime, the Tentacloid and Scorpion. Go for the eyes! This is full-tilt, out-of-this-world action! Surrealistic graphics plus true-to-life, earsplitting arcade pinball sound.[CR] - CHEATS - [CR][CR]View score during gameplay[CR]Press select while pausing.[CR]See The Ending[CR]Achieve a score of 999,999,900 points and the ending will start.[CR]1 Million Points + Bonus Ball[CR]Get to the bonus round with skulls and green aliens. Kill everything except for one skull. Keep going until a pteradactyl appears. Hit the pteradactyl with the ball to get a million points and a bonus ball once the stage is cleared.[CR]</plot>					<genre>Action</genre>					<releasedate>01/01/1989</releasedate>					<videoid>Bmqte-TrB6w</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8186-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/3/9/51539_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/8186-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/1/8/d/gfs_4860_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/9/6/a/gfs_57378_1_1.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/4/2/8/gfs_57378_1_2_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/0/6/b/gfs_57378_1_3_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/d/a/2/gfs_57378_1_4_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/9/e/1/gfs_57378_1_5_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/b/1/0/gfs_4860_2_1.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/1/c/0/gfs_4860_2_2.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/e/e/c/gfs_57378_2_1_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/2/2/9/gfs_57378_2_2_mid.jpg</snapshot10>			</game>			<game name="Andre' Panza Kick Boxing (USA)">						<description>Andre' Panza Kick Boxing (USA)</description>						<rom crc="a980e0e9" name="Andre' Panza Kick Boxing (USA).pce" sha1="B21023FCF1B16B8EF9890E8087BAB71A43253700" size="524288"/>					<plot>Forget the movies. Forget the make-believe. This is the master, 3 time World Kick Boxing Champion Andr Panza, and the reality will stun you! His every move was filmed and digitized over 2 years for a devastating arsenal of kick boxing combat. Train until you're good enough. Then go to war against a friend or battle through the ranks of 8 international champions! Over 50 whirlwind punches and kicks let you customize your attack. Master new techniques during hundreds of ever-changing battles. Then put your body on the line against Panza himself for the ultimate Kick Boxing Championship!</plot>					<genre>Fighting</genre>					<releasedate>01/01/1991</releasedate>					<nplayers>2</nplayers>					<videoid>_kEaGqX31EU</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8187-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/4/6/51546_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/8187-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/0/f/f/gfs_57380_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/a/6/2/gfs_57380_2_1.jpg</snapshot2>			</game>			<game name="Ballistix (USA)">						<description>Ballistix (USA)</description>						<rom crc="420fa189" name="Ballistix (USA).pce" sha1="8F65C5B459B477ADC97AB7809CA8E85329F25769" size="262144"/>					<plot>Sick of silly old soccer? Tired of pathetic pinball? Then you need a dose of Ballistix - the fastest, wackiest, toughest ball game yet to appear on a computer. Ballistix just explodes with excitement, puzzles and an amazing 130 different screens of frenetic action! The aim of the game is simple: score more goals than your opponent to win the match. Doing it is a different matter as splitters fill the screen with dozens of balls, tunnels hide them from view, bumpers bounce balls all over the show, fiendish red arrows speed them up to almost impossible velocity, magnets pull them away from your control, and much, much more. You can play against the computer or another player, set the speed if you can't stand the pace, define where the balls are fired and their velocity, rack up bonuses that will get you extra goals and then, at the end of an exhausting game, set your name in pride of place on the high-score table.</plot>					<genre>Action</genre>					<releasedate>01/01/1992</releasedate>					<nplayers>2</nplayers>					<videoid>wBbkhqtxl3Y</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8188-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/2/2/7/26227_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/8188-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/4/b/c/gfs_57381_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/a/3/6/gfs_57381_1_2_mid.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/e/7/5/gfs_57381_1_3_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/3/b/c/gfs_57381_1_4_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/7/f/f/gfs_57381_1_5_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/b/3/a/gfs_57381_1_6_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/f/7/9/gfs_57381_1_7_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/e/2/1/gfs_57381_2_1.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/4/f/1/gfs_57381_2_2.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/8/7/4/gfs_57381_2_3_mid.jpg</snapshot10>			</game>			<game name="Battle Royale (USA)">						<description>Battle Royale (USA)</description>						<rom crc="e70b01af" name="Battle Royale (USA).pce" sha1="07B39D5315AA07BF880B89B10DC3C01ED7CED5AB" size="524288"/>					<plot>It's wrestling mayhem out of control! Five maniacs hit the mat in a no-holds-barred, free-for-all brawl with no rules, no refs and absolutely no mercy! Team up with friends to nail opponents. Now look out! They're coming after you! Smash 'em, bash 'em and throw 'em over the ropes! The sound is so intense you'll feel every crushing hit, every cracking bone. It's furious, non-stop action for up to five players ... a winner-take-all gang fight for survival!</plot>					<genre>Sports</genre>					<releasedate>01/01/1990</releasedate>					<nplayers>4+</nplayers>					<videoid>KZw84ct2XIE</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8189-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/5/3/51553_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/8189-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/c/b/5/gfs_40517_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/d/6/f/gfs_40517_1_2_mid.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/9/2/c/gfs_40517_1_3_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/4/e/5/gfs_40517_1_4_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/0/a/6/gfs_40517_1_5_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/c/6/3/gfs_40517_1_6_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/8/2/0/gfs_40517_1_7_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/7/f/1/gfs_40517_1_8_mid.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/3/b/2/gfs_40517_1_9_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/0/f/b/gfs_40517_1_10_mid.jpg</snapshot10>			</game>			<game name="Blazing Lazers (USA)">						<description>Blazing Lazers (USA)</description>						<rom crc="b4a1b0f6" name="Blazing Lazers (USA).pce" sha1="13712AAEE596AD96AB743D5E82ED96895089AFEB" size="393216"/>					<plot>Blazing Lazers is a top-down shooter featuring 9 levels of varied and fast-paced action. The story here is the usual save-the-world variety. You must pilot your ship against 8 super-weapons and ultimately destroy the menace once and for all.The power-up system in Blazing Lazers deserves special mention. There are four main types of weapons, and each type of weapon can be upgraded several times to produce an incredible amount of firepower. In addition, there are secondary weapons systems that provide you with shields, homing missiles, multi-fire units, or super weapon power.[CR] - CHEATS - [CR]Debug Mode[CR]Enable Sound Test cheat. Press I, II, than keep pressing Select until the debug screen appears. You can now do the following: [CR]16 Lives, 36 Bombs and Double Score[CR]Don't shoot any bosses who are on odd numbered levels (1,3,5 etc). You will receive the lives, bombs and score when the boss leaves.[CR]</plot>					<genre>Action</genre>					<releasedate>01/01/1989</releasedate>					<videoid>8KnKE37A65o</videoid>					<fanart1>http://thegamesdb.net/banners/fanart/original/5657-1.jpg</fanart1>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/5657-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/6/9/51569_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/5657-1.jpg</boxart3>					<snapshot1>http://thegamesdb.net/banners/screenshots/5657-1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/a/4/b/gfs_4303_1_1.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/6/a/4/gfs_57389_1_1.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/9/5/b/gfs_57389_1_2_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/d/1/8/gfs_57389_1_3_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/0/d/1/gfs_57389_1_4_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/4/9/2/gfs_57389_1_5_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/8/5/7/gfs_57389_1_6_mid.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/c/1/4/gfs_57389_1_7_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/3/c/5/gfs_57389_1_8_mid.jpg</snapshot10>			</game>			<game name="Bloody Wolf (USA)">						<description>Bloody Wolf (USA)</description>						<rom crc="37baf6bc" name="Bloody Wolf (USA).pce" sha1="45F8762414FB6B581B6159908CC35B2607ECF237" size="524288"/>					<plot>Snake and Eagle, two commandos of the Bloody Wolf special forces, receive instructions from their commander to destroy the enemy's heavily armed base to rescue the President and any allies who have been reported as MIA.Based off the 1988 arcade game, this single-player, top-down, run and gun shooter takes a nod to Contra-style gameplay, allowing one of the two mercenaries to blast their way through eight levels of enemy opposition armed with only a knife and a machine gun. Along the way, new weapons such as shotguns, bazookas, flash bombs and grenades grenades can be added to the arsenal, as well as health and defensive power-ups. Players can even find a motorcycle to ride in some areas, or swim through certain parts of a level.The President and your fellow soldiers need you![CR] - CHEATS - [CR]Cheat Codes[CR]At the title screen, press Up, I, Down, II, Left, I, Right, II. A sound will be heard if entered correctly.[CR]</plot>					<genre>Action</genre>					<releasedate>01/01/1990</releasedate>					<videoid>V3i4bdPzQjc</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8190-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/6/3/51563_front.jpg</boxart2>					<snapshot1>http://img.gamefaqs.net/screens/3/6/4/gfs_40518_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/8/5/a/gfs_40518_1_2_mid.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/c/1/9/gfs_40518_1_3_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/1/d/0/gfs_40518_1_4_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/5/9/3/gfs_40518_1_5_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/9/5/6/gfs_40518_1_6_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/d/1/5/gfs_40518_1_7_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/9/f/9/gfs_40518_2_1.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/e/5/b/gfs_40518_2_2_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/a/1/8/gfs_40518_2_3_mid.jpg</snapshot10>			</game>			<game name="Bomberman (USA)">						<description>Bomberman (USA)</description>						<rom crc="5f6f3c2a" name="Bomberman (USA).pce" sha1="DC63680E579764BBACB7F07514F4F49AB888D3B1" size="262144"/>					<plot>The black spaceman kidnapped Bomberman's beloved and brought her to his chambers in the castle, far beyond his reach, over the rivers, forest and mountains. Bomberman's job is to save her, battling the sea of the enemies, with only bombs at his disposal.The range of Bomberman's bomb explosions can be upgraded with time, but if he dies, the range resets back to the minimum range and Bomberman loses his previous skills. Some updates can make Bomberman walk through the walls, increase his speed, and give him some other assets to aid him in his quest to save the woman he loves.This top-down action-arcade game consists of nine levels per stage, each tougher than the other, and each final one consisting of the boss that will have to be dealt with. Bomberman can move horizontally and vertically and lay down bombs behind him, thus evaporating the enemies, but beware: Bomberman can block himself with his own bomb, and thus become a victim of his own bomb.[CR] - CHEATS - [CR]Stage and Item Select[CR]Start a new game and get 300 points as your Hi Score. Lose all your lives and select &amp;quot;End&amp;quot; to go back to the title screen. Now, wait until the Demo screen appears and once it ends, as the title screen unfolds, hold Down + Button 1 + Button 2 + Select and press Run to start the game. When the intro is shown, press Run again (while still holding the buttons) and you'll enter the Stage and Item select screen.[CR]Hidden Bonus Point Items[CR]These items award you large amounts of points upon collection, but are all very difficult to find.[CR]</plot>					<genre>Puzzle</genre>					<releasedate>01/01/1990</releasedate>					<videoid>reKN7IBUakY</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/5658-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/7/9/51579_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/5658-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/3/c/1/gfs_4305_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/b/c/1/gfs_57390_1_1.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/2/c/5/gfs_57390_1_2_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/6/8/6/gfs_57390_1_3_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/b/4/f/gfs_57390_1_4_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/f/0/c/gfs_57390_1_5_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/3/c/9/gfs_57390_1_6_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/7/8/a/gfs_57390_1_7_mid.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/8/5/b/gfs_57390_1_8_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/c/1/8/gfs_57390_1_9_mid.jpg</snapshot10>					<clearlogo1>http://thegamesdb.net/banners/clearlogo/5658.png</clearlogo1>			</game>			<game name="Bomberman '93 (USA)">						<description>Bomberman '93 (USA)</description>						<rom crc="56171c1c" name="Bomberman '93 (USA).pce" sha1="709B47DE6E0EBC18FB80C951D5CFAA6CE82D6CE0" size="524288"/>					<plot>Tension, strategy, action, excitement - Bomberman's back!You can now battle against up to four computer-controlled maniacs by yourself for the ultimate five bomberman mode.Choose from seven exciting new stages with loads of new power-up items like werps, conveyer belts, revolving doors and even kicking bombs!Or for portable thrills, go head-to-head against a friend using TurboExpress for non-stop action.The best competitive game is back, and it's more intense than ever![CR] - CHEATS - [CR]Debug Menu (Japanese Version)[CR]After the ending, when the &amp;quot;END&amp;quot; screen is displayed, wait until the music is over, hold Button 1 and press Run. If done right a sound will be heard. Now, hold Run and press Select to soft-reset the game. Start a Normal game and before the level starts, you'll get the debug menu.[CR]</plot>					<genre>Action</genre>					<releasedate>01/01/1993</releasedate>					<nplayers>4+</nplayers>					<videoid>hywbi9l6k3o</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/8191-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/6/0/0/51600_front.jpg</boxart2>					<boxart3>http://thegamesdb.net/banners/boxart/original/back/8191-1.jpg</boxart3>					<snapshot1>http://img.gamefaqs.net/screens/f/0/4/gfs_4306_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/2/4/6/gfs_4306_1_2_mid.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/6/0/5/gfs_4306_1_3_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/b/c/c/gfs_4306_1_4_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/f/8/f/gfs_4306_1_5_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/3/4/a/gfs_4306_1_6_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/7/0/9/gfs_4306_1_7_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/8/d/8/gfs_4306_1_8_mid.jpg</snapshot8>					<snapshot9>http://img.gamefaqs.net/screens/c/9/b/gfs_4306_1_9_mid.jpg</snapshot9>					<snapshot10>http://img.gamefaqs.net/screens/a/8/8/gfs_4306_1_10_mid.jpg</snapshot10>			</game>			<game name="Bonk III - Bonk's Big Adventure (USA)">						<description>Bonk III - Bonk's Big Adventure (USA)</description>						<rom crc="5a3f76d8" name="Bonk III - Bonk's Big Adventure (USA).pce" sha1="B966DF0281F7FAB4536AFC166278E1BEC0D926C4" size="1048576"/>					<plot>Aaagh! What's that Evil King drool doing back in the Dinosaur Kingdom?! Didn't Bonk get rid of him last time? Guess not, huh? Now it's up to our skull-splitting, head-butting, rock-smashing, monster-bashing prehistoric hero Bonk to put an end to Drool's dastardly deeds once and for all! Watch Bonk grown into huge fire-breathing Bonk or shrink into the Mini-Size Bonk and take on tons of cool new enemies like RocketMan, Robo Turtle and Crazy Lady. Or how about smashing up a few Booga Boogas or Snippies along the way. It's the ultimate bash-o-rama![CR] - CHEATS - [CR]Cheat Mode[CR]First enter the &amp;quot;Cheat Menu&amp;quot; code. Once in the menu, press Select and the game will automatically start with invincibility.[CR]</plot>					<genre>Action</genre>					<releasedate>12/01/1994</releasedate>					<videoid>6nuU-qYZC0M</videoid>					<boxart1>http://thegamesdb.net/banners/boxart/original/front/13876-1.jpg</boxart1>					<boxart2>http://img.gamefaqs.net/box/5/8/9/51589_front.jpg</boxart2>					<snapshot1>http://img.gamefaqs.net/screens/f/8/2/gfs_57391_1_1.jpg</snapshot1>					<snapshot2>http://img.gamefaqs.net/screens/b/4/0/gfs_57391_1_2_mid.jpg</snapshot2>					<snapshot3>http://img.gamefaqs.net/screens/f/0/3/gfs_57391_1_3_mid.jpg</snapshot3>					<snapshot4>http://img.gamefaqs.net/screens/2/c/a/gfs_57391_1_4_mid.jpg</snapshot4>					<snapshot5>http://img.gamefaqs.net/screens/6/8/9/gfs_57391_1_5_mid.jpg</snapshot5>					<snapshot6>http://img.gamefaqs.net/screens/a/4/c/gfs_57391_1_6_mid.jpg</snapshot6>					<snapshot7>http://img.gamefaqs.net/screens/e/0/f/gfs_57391_1_7_mid.jpg</snapshot7>					<snapshot8>http://img.gamefaqs.net/screens/